### ISSUE TITLE
Error "set_session cannot be used inside a transaction" using postgres (tag: latest)

### ISSUE THREAD

**Issue by hangrymuppet** [meeb/tubesync#135]
Error below:

```Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    main()
  File "/app/manage.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/background_task/management/commands/process_tasks.py", line 123, in handle
    self.run(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/background_task/management/commands/process_tasks.py", line 105, in run
    if not self._tasks.run_next_task(queue):
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 137, in run_next_task
    return self._runner.run_next_task(self, queue)
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 261, in run_next_task
    task = self.get_task_to_run(tasks, queue)
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 245, in get_task_to_run
    available_tasks = [task for task in Task.objects.find_available(queue)
  File "/usr/local/lib/python3.7/dist-packages/background_task/models.py", line 57, in find_available
    currently_failed = self.failed().count()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/query.py", line 519, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/query.py", line 504, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/app/tubesync/dbutils.py", line 20, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 201, in connect
    self.set_autocommit(self.settings_dict['AUTOCOMMIT'])
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 415, in set_autocommit
    self._set_autocommit(autocommit)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/base.py", line 277, in _set_autocommit
    self.connection.autocommit = autocommit
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/base.py", line 277, in _set_autocommit
    self.connection.autocommit = autocommit
django.db.utils.ProgrammingError: set_session cannot be used inside a transaction```

**Comment by meeb** [comment]
Looks like an introduced bug with psysopg2, again... or if not a bug an increase in strictness in what it will accept (or possibly with a stricter / more modern PostgreSQL server than I tested with).

This is caused by a "keep-alive" hack to keep MySQL connections open which is now apparently not permitted with the latest Postgres library. I'll look into if there's a way to toggle off transactions for the keep-alive which should fix this.
