### ISSUE TITLE
Latest Docker images appear to be missing libjpeg

### ISSUE THREAD

**Issue by scottwallacesh** [meeb/tubesync#149]
```plain
[2021-09-04 07:49:37 +0100] [1399] [INFO] Starting gunicorn 20.1.0
[2021-09-04 07:49:37 +0100] [1399] [INFO] Listening at: http://127.0.0.1:8080 (1399)
[2021-09-04 07:49:37 +0100] [1399] [INFO] Using worker: sync
[2021-09-04 07:49:37 +0100] [1405] [INFO] Booting worker with pid: 1405
[2021-09-04 07:49:38 +0100] [1407] [INFO] Booting worker with pid: 1407
[2021-09-04 07:49:38 +0100] [1408] [INFO] Booting worker with pid: 1408
2021-09-04 07:49:38,141 [tubesync/INFO] Using database connection: django.db.backends.mysql://tubesync:[hidden]@mysql:3306/tubesync
2021-09-04 07:49:38,240 [tubesync/INFO] Using database connection: django.db.backends.mysql://tubesync:[hidden]@mysql:3306/tubesync
2021-09-04 07:49:38,287 [tubesync/INFO] Using database connection: django.db.backends.mysql://tubesync:[hidden]@mysql:3306/tubesync
2021-09-04 07:49:38,328 [tubesync/INFO] Using database connection: django.db.backends.mysql://tubesync:[hidden]@mysql:3306/tubesync
[2021-09-04 07:49:38 +0100] [1405] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/tubesync/wsgi.py", line 6, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.7/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/sync/models.py", line 18, in <module>
    from .utils import seconds_to_timestr, parse_media_format
  File "/app/sync/utils.py", line 6, in <module>
    from PIL import Image
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory
[2021-09-04 07:49:38 +0100] [1405] [INFO] Worker exiting (pid: 1405)
```

**Comment by meeb** [comment]
Thanks, added manually now. Minor fallout from the Pillow3 lib upgrade.
