### ISSUE TITLE
Age confirmation

### ISSUE THREAD

**Issue by MatthK** [meeb/tubesync#151]
A few tasks keep failing with the following error messages. It seems it can't download them as there is an age check for the content.

```
2021-09-06 15:14:55,584 [tubesync/DEBUG] [youtube] wCu54XofcOs: Downloading webpage
2021-09-06 15:14:55,866 [tubesync/DEBUG] [youtube] wCu54XofcOs: Refetching age-gated info webpage
2021-09-06 15:14:55,931 [tubesync/WARNING] unable to download video info webpage: HTTP Error 410: Gone
2021-09-06 15:14:55,931 [tubesync/ERROR] ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Rescheduling Downloading metadata for "b97cf2d1-4530-4a01-8b0d-44bb80665a91"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 226, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1234, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 50, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=wCu54XofcOs": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "b97cf2d1-4530-4a01-8b0d-44bb80665a91" for 0:10:30 later at 2021-09-06 07:25:25.938072+00:00
2021-09-06 15:15:00,631 [tubesync/DEBUG] [youtube] uWEp_4fHX4Y: Downloading webpage
2021-09-06 15:15:01,017 [tubesync/DEBUG] [youtube] uWEp_4fHX4Y: Refetching age-gated info webpage
2021-09-06 15:15:01,071 [tubesync/WARNING] unable to download video info webpage: HTTP Error 410: Gone
2021-09-06 15:15:01,072 [tubesync/ERROR] ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Rescheduling Downloading metadata for "46d014eb-8d4a-4d43-9647-3a7960ba7a1e"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 226, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1234, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 50, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=uWEp_4fHX4Y": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "46d014eb-8d4a-4d43-9647-3a7960ba7a1e" for 0:10:30 later at 2021-09-06 07:25:31.078598+00:00
```

Surprisingly, these don't shop up as errors in the tasks list.

**Comment by meeb** [comment]
The download task will show up as an error once it's failed enough times. It'll try repeatedly for a while then mark it as failed. The actual error is caused because `youtube-dl` can't download the video as it has an age restriction applied to it. There are attempts at work-arounds in forks of `youtube-dl` such as in `yt-dlp`.

Here's the upstream issue for `youtube-dl`: https://github.com/ytdl-org/youtube-dl/issues/28578

This may improve after the pending switch to `yt-dlp`, however at the core of the issue is working around YouTube's restrictions. If implemted in a way that work-arounds no longer work successfully the only method may be to either accept TubeSync can't download age restricted videos or implement support for `cookies.txt` or some other authentication method with YouTube. This of course would start identifying Google accounts as using TubeSync to Google again though as discussed in the previous issue on API keys so neither is an ideal solution unfortunately.
