### ISSUE TITLE
Failed to find an upload date leading to, `TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'`

### ISSUE THREAD

**Issue by scottwallacesh** [meeb/tubesync#191]
```
2021-12-09T14:53:22.639681929Z 2021-12-09 14:53:22,639 [tubesync/ERROR] Media has no upload date, skipping: example / 3adq1KeSD14
2021-12-09T14:53:22.639997417Z Rescheduling Downloading metadata for "62d96aa1-7807-4cea-b712-3fd3d5d565e6"
2021-12-09T14:53:22.640004751Z Traceback (most recent call last):
2021-12-09T14:53:22.640009779Z   File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
2021-12-09T14:53:22.640014319Z     func(*args, **kwargs)
2021-12-09T14:53:22.640018929Z   File "/app/sync/tasks.py", line 239, in download_media_metadata
2021-12-09T14:53:22.640024237Z     if media.published < max_cap_age:
2021-12-09T14:53:22.640029406Z TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
2021-12-09T14:53:22.647301749Z Rescheduling task Downloading metadata for "62d96aa1-7807-4cea-b712-3fd3d5d565e6" for 0:10:30 later at 2021-12-09 15:03:52.647045+00:00
```

**Comment by meeb** [comment]
Thanks for the issue. This was caused by your video (in the log, this one https://www.youtube.com/watch?v=3adq1KeSD14) being removed and so has no metadata (and with no metadata no published date to compare against). I've added a check to stop this exception from being raised. You will still see ERROR's in the logs though as the video is obviously broken.
