### ISSUE TITLE
Task Reset failing because of locked database

### ISSUE THREAD

**Issue by awkw4rdkid** [meeb/tubesync#195]
Hey there, love where this project is going so just want to say thanks so much for working on it! I've been having some issues where the whole thing crashes and tasks aren't processing at all. In the past I've just been able to hit the Task Reset button and go on my merry way but recently it's only been scheduling tasks for 2 of my 20 sources. If I run the command for docker like you have in the documentation, I get the following error after those two sources (from what I can tell, nothing is running at the time this happens):

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    main()
  File "/app/manage.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/sync/management/commands/reset-tasks.py", line 32, in handle
    source.save()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.9/dist-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.9/dist-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/app/sync/signals.py", line 65, in source_post_save
    media.save()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked`

**Comment by meeb** [comment]
Depending on the number of channels or and media items you're trying to download you may be better off using a Postgres backend. You can also use a command line task reset which should work regardless of what the UI is doing. "Database is locked" with SQLite pretty much means both the UI and worker tried to write at the same time. SQLite supports only one write at a time, but multiple reads. There's some "advanced" guides here:

https://github.com/meeb/tubesync/blob/main/docs/reset-tasks.md

https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md

**Comment by awkw4rdkid** [comment]
Thanks, I'll take a look at the postgres options and see if that helps at all. It seems like if I run it from the command line a couple of times it gets a little farther each time so maybe there's something going on in the background still and I'm just not seeing it?

**Comment by meeb** [comment]
Yes that sounds likely. If anything tries a write to the database while the `reset-tasks` script is running it'll fail on SQLite at the moment. Postgres or MySQL backends do not have this limitation. Ideally this should be in a queue and avoid multiple writes entirely given TubeSync isn't actually that write-heavy, but that's not written yet.

**Comment by awkw4rdkid** [comment]
Just got the Postgres DB set up. Seems to be working better! One thing I did notice in your documentation, if you're running without TTY (I'm using Ubuntu Server 21.04 for my Docker host), I was only able to use -i instead of -ti for the loaddata command for Django. Thanks so much for your help and I can't wait to see where this project goes!

**Comment by meeb** [comment]
Thanks for the feedback, I'll check the docs for that later. Glad you got it resolved in the end!
