### ISSUE TITLE
Keep Rescheduling Task

### ISSUE THREAD

**Issue by plsharevme** [meeb/tubesync#230]
Change to database postgresql it more smooth and worker seem to do their jobs very well.

After add few sources, it keep downloading the thumbnail and meta, and index media working as promise. 

Scheduled jobs keep reduce after download metadata & thumbnail, eventually  finish download and left the **downloading media**.

It just stop there, no progress anymore.

The sources i add is anime, is a paid member to view the latest episode anime, in the list let say have 20 episode anime, the latest update 1 is only for members, after 2 week or so it will open public.

From the logs i found out tubesync no progress cause it keep rescheduling the member only video.

example source i add.
```
https://www.youtube.com/playlist?list=PLOUUm4xsoaeA8BMJ5tVELTJnLBq_6pcZl
https://www.youtube.com/playlist?list=PLOUUm4xsoaeCqC2PtoUeNlwWxnU5o1YP2
https://www.youtube.com/playlist?list=PLOUUm4xsoaeAScNvGCgdTzTSqRPsFkicX
```
It have successful download few media at start if rotate to members only video it no smart enough to skip to next video.

Here is the logs file.
<details>
  <summary>Click to expand!</summary>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=BR-eZ8bZTjw": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "3e7662df-a92e-4b09-855f-b2e665e3ddbc" for 0:21:41 later at 2022-04-07 17:41:38.769723+00:00
2022-04-08 01:20:14,080 [tubesync/DEBUG] [youtube] QLMd3Xq2ga4: Downloading webpage
2022-04-08 01:20:14,607 [tubesync/DEBUG] [youtube] QLMd3Xq2ga4: Downloading android player API JSON
2022-04-08 01:20:14,722 [tubesync/ERROR] ERROR: [youtube] QLMd3Xq2ga4: Join this channel to get access to members-only content like this video, and other exclusive perks.
Rescheduling Downloading metadata for "f607734e-a05f-4a98-b871-8f76a892f2ca"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=QLMd3Xq2ga4": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "f607734e-a05f-4a98-b871-8f76a892f2ca" for 0:21:41 later at 2022-04-07 17:42:03.040169+00:00
2022-04-08 01:20:41,757 [tubesync/DEBUG] [youtube] fFNAd5iZbC4: Downloading webpage
2022-04-08 01:20:42,233 [tubesync/DEBUG] [youtube] fFNAd5iZbC4: Downloading android player API JSON
2022-04-08 01:20:42,330 [tubesync/ERROR] ERROR: [youtube] fFNAd5iZbC4: Join this channel to get access to members-only content like this video, and other exclusive perks.
Rescheduling Downloading metadata for "4358e886-345f-4c13-a2b7-972522c779c2"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=fFNAd5iZbC4": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "4358e886-345f-4c13-a2b7-972522c779c2" for 0:21:41 later at 2022-04-07 17:42:35.333761+00:00
2022-04-08 01:21:13,021 [tubesync/DEBUG] [youtube] EoIXJCToIMc: Downloading webpage
2022-04-08 01:21:13,469 [tubesync/DEBUG] [youtube] EoIXJCToIMc: Downloading android player API JSON
2022-04-08 01:21:13,563 [tubesync/ERROR] ERROR: [youtube] EoIXJCToIMc: Join this channel to get access to members-only content like this video, and other exclusive perks.
Rescheduling Downloading metadata for "d81bc27b-06de-43d9-9289-0fde66b84afe"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=EoIXJCToIMc": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "d81bc27b-06de-43d9-9289-0fde66b84afe" for 0:21:41 later at 2022-04-07 17:43:00.523608+00:00
2022-04-08 01:21:49,289 [tubesync/DEBUG] [youtube] Z5ChwjkIMo8: Downloading webpage
2022-04-08 01:21:49,911 [tubesync/DEBUG] [youtube] Z5ChwjkIMo8: Downloading android player API JSON
2022-04-08 01:21:50,000 [tubesync/ERROR] ERROR: [youtube] Z5ChwjkIMo8: Join this channel to get access to members-only content like this video, and other exclusive perks.
Rescheduling Downloading metadata for "79acf7ec-bf4f-4e03-bb48-ea12745cf81b"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=Z5ChwjkIMo8": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "79acf7ec-bf4f-4e03-bb48-ea12745cf81b" for 0:21:41 later at 2022-04-07 17:43:39.749618+00:00
2022-04-08 01:22:15,388 [tubesync/DEBUG] [youtube] S7-I_jQK3iU: Downloading webpage
2022-04-08 01:22:15,829 [tubesync/DEBUG] [youtube] S7-I_jQK3iU: Downloading android player API JSON
2022-04-08 01:22:15,933 [tubesync/ERROR] ERROR: [youtube] S7-I_jQK3iU: Join this channel to get access to members-only content like this video, and other exclusive perks.
Rescheduling Downloading metadata for "98fc635a-bf89-432c-beab-b6a5d5f49d91"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=S7-I_jQK3iU": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "98fc635a-bf89-432c-beab-b6a5d5f49d91" for 0:21:41 later at 2022-04-07 17:44:11.404044+00:00
2022-04-08 01:22:45,699 [tubesync/DEBUG] [youtube] BWuA4qc7bmY: Downloading webpage
2022-04-08 01:22:46,219 [tubesync/DEBUG] [youtube] BWuA4qc7bmY: Downloading android player API JSON
2022-04-08 01:22:46,313 [tubesync/ERROR] ERROR: [youtube] BWuA4qc7bmY: Join this channel to get access to members-only content like this video, and other exclusive perks.
Rescheduling Downloading metadata for "59966c10-9f29-4f22-8d1f-f4cc35f51b6f"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=BWuA4qc7bmY": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
</details>

**Comment by meeb** [comment]
If you click any of the videos in your log that are failing (for example, https://www.youtube.com/watch?v=BR-eZ8bZTjw ) you'll note that they are "members only" and require a login to access. Test them in an incognito / private browser window to check. TubeSync isn't authenticated to YouTube, so it can't download videos behind a login wall.

You can (at your own risk) use authentication cookies exported from your browser with TubeSync so TubeSync can "log in" as you, here's the guide:

https://github.com/meeb/tubesync/blob/main/docs/using-cookies.md

Carefully read and understand the warning before you try this though.
