### ISSUE TITLE
Can't detect cookies.txt

### ISSUE THREAD

**Issue by Toylerrr** [meeb/tubesync#259]
Unraid Docker

folder /config <->/mnt/user/appdata/tubesync
```
#ls -la
drwxr-xr-x 1 app  users       62 Aug  3 21:17 .
drwxr-xr-x 1 root root       218 Aug  3 21:07 ..
drwxr-xr-x 1 app  users       56 Aug  3 20:49 cache
-rwxr-xr-x 1 app  users     2306 Aug  3 20:22 cookies.txt
-rwxr-xr-x 1 app  users 11186176 Aug  3 21:17 db.sqlite3
drwxr-xr-x 1 app  users       12 Aug  3 19:46 media
```

Can't seem to get the Tubesync docker to detect cookies.txt

Would there be a way to force the selection of the cookies.txt file?

**Comment by meeb** [comment]
Are you sure they aren't being detected? The only notice at the moment that the `cookies.txt` file is being used is a line in the logs that will look something like this every time some media is downloaded:

```
YYYY-mm-dd HH:ii:ss [youtube-dl] using cookies.txt from: /app/cookies.txt
```

or similar.

**Comment by Toylerrr** [comment]
Yes i'm sure it isn't being detected this is the full error i'm getting, I am a member of the channel and i'm not getting the invalid cookies error either 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=JzBJvHKPr44": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "ace2fd6e-2671-401c-9c1b-d6f3a05dc425" for 5:45:41 later at 2022-08-05 21:04:02.576165+00:00
2022-08-05 08:18:23,780 [tubesync/DEBUG] [youtube] _ZHJWe8OVF0: Downloading webpage
2022-08-05 08:18:23,845 [tubesync/DEBUG] [youtube] Ng2sz250b8M: Downloading webpage
2022-08-05 08:18:24,150 [tubesync/DEBUG] [youtube] _ZHJWe8OVF0: Downloading android player API JSON
2022-08-05 08:18:24,254 [tubesync/DEBUG] [youtube] Ng2sz250b8M: Downloading android player API JSON
2022-08-05 08:18:24,283 [tubesync/ERROR] ERROR: [youtube] _ZHJWe8OVF0: Join this channel to get access to members-only content like this video, and other exclusive perks.
Rescheduling Downloading metadata for "bd9aa14c-ab86-4e8d-9d27-6605f489321a"
```

**Comment by meeb** [comment]
Once built, update your container and try that. It was looking for the cookies file in the application directory not the container config directory which should be resolved now.
