### ISSUE TITLE
This source has encountered permanent failures listed at the bottom of this page, check its settings 

### ISSUE THREAD

**Issue by csjoh** [meeb/tubesync#298]
Hello,

I'm having trouble with one specific channel, Johnny Harris: https://www.youtube.com/c/johnnyharris/videos

The problem is a bit of an odd one, as I can successfully add the channel to my existing container or to a brand new one and it will start indexing videos and even download many of them, but at some point it just stops doing what it's supposed to do and breaks, leading to the results below.

I'm really hoping this can be solved. If you need more logs, information, command output, etc., let me know.

_Environment:_
* Host: Dell Poweredge T430 server, unRAID 6.9.2 x64
* Docker: Yes, via unRAID template
* Tubesync version: ghcr.io/meeb/tubesync:latest ; TubeSync version 0.11.0 with yt-dlp version 2022.09.01 and FFmpeg version 4.3.4-0+deb11u1.
* Reverse proxy: Yes, NGINX (manual config)
* SSL: Yes, Let's Encrypt, terminated on reverse proxy host

Tubesync reports: "This source has encountered permanent failures listed at the bottom of this page, check its settings"

Scrolling down, I find:

```
 Index media from source "Johnny Harris"
Error: "(1366, "Incorrect string value: '\\xF0\\x9D\\x97\\x94\\xF0\\x9D...' for column `tubesyncvideo`.`background_task`.`verbose_name` at row 1")"
Occured at 2023-01-05 20:14:40 

Trying to edit the source, I get this:

<h1>OperationalError
       at /source-update/68c632c8-5e1f-40a2-afe4-8311a813affb</h1>
  <pre class="exception_value">(1366, "Incorrect string value: '\\xF0\\x9D\\x97\\x94\\xF0\\x9D...' for column `tubesyncvideo`.`background_task`.`verbose_name` at row 1")</pre>
  

Request Method: | POST
-- | --
http://localhost/source-update/68c632c8-5e1f-40a2-afe4-8311a813affb
3.2.15
OperationalError
(1366, "Incorrect string value: '\\xF0\\x9D\\x97\\x94\\xF0\\x9D...' for column `tubesyncvideo`.`background_task`.`verbose_name` at row 1")
/usr/local/lib/python3.9/dist-packages/MySQLdb/cursors.py, line 352, in _get_result
/usr/bin/python3
3.9.2
['/usr/local/bin',  '/app',  '/usr/lib/python39.zip',  '/usr/lib/python3.9',  '/usr/lib/python3.9/lib-dynload',  '/usr/local/lib/python3.9/dist-packages',  '/usr/lib/python3/dist-packages']
Thu, 05 Jan 2023 20:36:48 +0100
```

**Traceback:**

```
Environment:


Request Method: POST
Request URL: http://localhost/source-update/68c632c8-5e1f-40a2-afe4-8311a813affb

Django Version: 3.2.15
Python Version: 3.9.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'sass_processor',
 'background_task',
 'common',
 'sync']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'common.middleware.MaterializeDefaultFieldsMiddleware',
 'common.middleware.BasicAuthMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()

The above exception ((1366, "Incorrect string value: '\\xF0\\x9D\\x97\\x94\\xF0\\x9D...' for column `tubesyncvideo`.`background_task`.`verbose_name` at row 1")) was the direct cause of the following exception:
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/app/sync/views.py", line 393, in form_valid
    return super().form_valid(form)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/usr/local/lib/python3.9/dist-packages/django/forms/models.py", line 468, in save
    self.instance.save()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.9/dist-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.9/dist-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/app/sync/signals.py", line 65, in source_post_save
    media.save()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.9/dist-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.9/dist-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/app/sync/signals.py", line 168, in media_post_save
    download_media_thumbnail(
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 293, in __call__
    return self.runner.schedule(self.name, args, kwargs, run_at, priority,
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 239, in schedule
    task.save()
  File "/usr/local/lib/python3.9/dist-packages/background_task/models.py", line 324, in save
    return super(Task, self).save(*arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/usr/local/lib/python3.9/dist-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()

Exception Type: OperationalError at /source-update/68c632c8-5e1f-40a2-afe4-8311a813affb
Exception Value: (1366, "Incorrect string value: '\\xF0\\x9D\\x97\\x94\\xF0\\x9D...' for column `tubesyncvideo`.`background_task`.`verbose_name` at row 1")
```

In the container log, the last message before the traceback is:

```
2023-01-05 20:14:40,086 [tubesync/ERROR] Permanent failure for source: Johnny Harris task: Index media from source "Johnny Harris" - 2023-01-05 19:14:40.029903+00:00
2023-01-05 20:14:42,735 [tubesync/INFO] Scheduling task to download thumbnail for: The Biggest Mapping Mistake of 𝗔𝗟𝗟 𝗧𝗜𝗠𝗘 from: https://i.ytimg.com/vi/Hcq9_Tw2eTE/maxresdefault.jpg
192.168.2.40 - USERNAME [05/Jan/2023:20:34:08 +0100] "GET /source-update/68c632c8-5e1f-40a2-afe4-8311a813affb HTTP/1.0" 200 18750 "https://TUBESYNC/source/68c632c8-5e1f-40a2-afe4-8311a813affb" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.2.40 - USERNAME [05/Jan/2023:20:34:09 +0100] "GET /static/fonts/roboto/roboto-regular.woff HTTP/1.0" 304 0 "https://TUBESYNC/static/styles/tubesync.css" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.2.40 - USERNAME [05/Jan/2023:20:34:09 +0100] "GET /static/fonts/fontawesome/fa-regular-400.woff2 HTTP/1.0" 304 0 "https://TUBESYNC/static/styles/tubesync.css" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.2.40 - USERNAME [05/Jan/2023:20:34:09 +0100] "GET /static/fonts/fontawesome/fa-solid-900.woff2 HTTP/1.0" 304 0 "https://TUBESYNC/static/styles/tubesync.css" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.2.40 - USERNAME [05/Jan/2023:20:34:09 +0100] "GET /static/fonts/fontawesome/fa-brands-400.woff2 HTTP/1.0" 304 0 "https://TUBESYNC/static/styles/tubesync.css" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.2.40 - USERNAME [05/Jan/2023:20:36:14 +0100] "GET /source/68c632c8-5e1f-40a2-afe4-8311a813affb HTTP/1.0" 200 178536 "https://TUBESYNC/sources" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.2.40 - USERNAME [05/Jan/2023:20:36:15 +0100] "GET /static/styles/tubesync.css HTTP/1.0" 200 188478 "https://TUBESYNC/source/68c632c8-5e1f-40a2-afe4-8311a813affb" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
2023-01-05 20:36:48,425 [tubesync/INFO] Scheduling task to download thumbnail for: The Biggest Mapping Mistake of 𝗔𝗟𝗟 𝗧𝗜𝗠𝗘 from: https://i.ytimg.com/vi/Hcq9_Tw2eTE/maxresdefault.jpg
Internal Server Error: /source-update/68c632c8-5e1f-40a2-afe4-8311a813affb
```

Deleting the source and media, then re-adding it, leads to the same problem.

I even spun up a dedicated instance using sqlite3 as the backend just to rule out interference from the other sources, but got the same result with that one as well.

**Comment by csjoh** [comment]
Oh yeah, I forgot: Adding the source by the old /c/channelname, the new @channelname or even by ID all yield the same result.

**Comment by meeb** [comment]
This is a MySQL encoding error. Did you create the MySQL database with the correct encoding? Like `utf8mb4`?

**Comment by csjoh** [comment]
> This is a MySQL encoding error. Did you create the MySQL database with the correct encoding? Like `utf8mb4`?

Yes... I think so...

I'll double check.

No, I did not.

```
MariaDB [tubesyncvideo]> show create database tubesyncvideo ;
+---------------+---------------------------------------------------------------------------+
| Database      | Create Database                                                           |
+---------------+---------------------------------------------------------------------------+
| tubesyncvideo | CREATE DATABASE `tubesyncvideo` /*!40100 DEFAULT CHARACTER SET utf8mb3 */ |
+---------------+---------------------------------------------------------------------------+
1 row in set (0.000 sec)
```
Can I change the encoding now, or do I need to nuke the database and start again?

**Comment by csjoh** [comment]
After a bit of googling, I found that I can indeed change the character set and collation after the database and tables have been created.

The magic commands are:

`# mysqldump -pPASSWORD databasename > databasename.sql`

I.e. ALWAYS MAKE A BACKUP!

Then:
```
# mysql -uroot -pPASSWORD

ALTER DATABASE databasename CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE tablename CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

I did get errors when trying to convert sync_media and sync_source due to foreign key checks, so I did this:

```
> SELECT @@FOREIGN_KEY_CHECKS;
1
> SET FOREIGN_KEY_CHECKS=0;
> SELECT @@FOREIGN_KEY_CHECKS;
0
```

Then I did ALTER TABLE for the two remaining tables. That took a while as they hold the bulk of the data (some 832MB of it) and the commands went through without errors. It must be noted that I am NOT very proficient in database manipulation - it's been many a year since I did any real database management, and what I did may very well be a Very Bad Thing(tm) to do and I may have borked my database to the point where it no longer works. If that's the case, I have a backup that I can restore then mess around with on another database server.

**Comment by csjoh** [comment]
Another quick followup:

Once the database had been converted, I had to edit the source and save it (no changes were made) and immediately the errors dissappeared and new tasks were created for the source, and it has started downloading.

Woo!

**Comment by meeb** [comment]
Yes, the issue was because in your original MySQL output your charset was `utf8mb3` and this needs to be `utf8mb4`. This is mentioned with a note in the docs. Thanks for your verbosity so others who stumble over this issue can fix it as well. Cheers! For reference: https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md (note the important note for MySQL).
