### ISSUE TITLE
TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by fmoledina** [meeb/tubesync#31]
I'm testing this out and I am getting errors for 3 of the videos with the same error from one channel: `TypeError: 'bool' object is not subscriptable` for the `acodec`. Somehow it's not picking up the MP4A fallback format for these files.

The videos are as follows:
* [Video 1](https://www.youtube.com/watch?v=sDIvfEJ59XY)
* [Video 2](https://www.youtube.com/watch?v=qdnJ02Phmhs)
* [Video 3](https://www.youtube.com/watch?v=DVD2Wm4jxlI)

Edit to add: I'm running v0.7 via Docker.

Docker log output is as follows:
```log
tubesync         | 2020-12-31T06:45:37.271334737Z Rescheduling Downloading media for "Realism Gets Even More Real: Crash Course Theater #32"
tubesync         | 2020-12-31T06:45:37.271384162Z Traceback (most recent call last):
tubesync         | 2020-12-31T06:45:37.271394256Z   File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
tubesync         | 2020-12-31T06:45:37.271404175Z     func(*args, **kwargs)
tubesync         | 2020-12-31T06:45:37.271411219Z   File "/app/sync/tasks.py", line 285, in download_media
tubesync         | 2020-12-31T06:45:37.271418468Z     filepath = media.filepath
tubesync         | 2020-12-31T06:45:37.271425576Z   File "/app/sync/models.py", line 1043, in filepath
tubesync         | 2020-12-31T06:45:37.271432561Z     return self.source.directory_path / self.filename
tubesync         | 2020-12-31T06:45:37.271439616Z   File "/app/sync/models.py", line 1010, in filename
tubesync         | 2020-12-31T06:45:37.271448879Z     media_details = self.format_dict
tubesync         | 2020-12-31T06:45:37.271458495Z   File "/app/sync/models.py", line 879, in format_dict
tubesync         | 2020-12-31T06:45:37.271465465Z     display_format = self.get_display_format(format_str)
tubesync         | 2020-12-31T06:45:37.271472406Z   File "/app/sync/models.py", line 841, in get_display_format
tubesync         | 2020-12-31T06:45:37.271481093Z     acodec = aformat['acodec'].lower()
tubesync         | 2020-12-31T06:45:37.271488194Z TypeError: 'bool' object is not subscriptable
tubesync         | 2020-12-31T06:45:37.279256328Z Rescheduling task Downloading media for "Realism Gets Even More Real: Crash Course Theater #32" for 0:10:30 later at 2020-12-31 06:56:07.278999+00:00
tubesync         | 2020-12-31T06:45:37.322813258Z Rescheduling Downloading media for "Hot Dog Contest 2014"
tubesync         | 2020-12-31T06:45:37.322875764Z Traceback (most recent call last):
tubesync         | 2020-12-31T06:45:37.322885741Z   File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
tubesync         | 2020-12-31T06:45:37.322894881Z     func(*args, **kwargs)
tubesync         | 2020-12-31T06:45:37.322901957Z   File "/app/sync/tasks.py", line 285, in download_media
tubesync         | 2020-12-31T06:45:37.322909094Z     filepath = media.filepath
tubesync         | 2020-12-31T06:45:37.322919566Z   File "/app/sync/models.py", line 1043, in filepath
tubesync         | 2020-12-31T06:45:37.322926625Z     return self.source.directory_path / self.filename
tubesync         | 2020-12-31T06:45:37.322933594Z   File "/app/sync/models.py", line 1010, in filename
tubesync         | 2020-12-31T06:45:37.322940517Z     media_details = self.format_dict
tubesync         | 2020-12-31T06:45:37.322947345Z   File "/app/sync/models.py", line 879, in format_dict
tubesync         | 2020-12-31T06:45:37.322955108Z     display_format = self.get_display_format(format_str)
tubesync         | 2020-12-31T06:45:37.322962066Z   File "/app/sync/models.py", line 841, in get_display_format
tubesync         | 2020-12-31T06:45:37.322969351Z     acodec = aformat['acodec'].lower()
tubesync         | 2020-12-31T06:45:37.322976192Z TypeError: 'bool' object is not subscriptable
tubesync         | 2020-12-31T06:45:37.332229543Z Rescheduling task Downloading media for "Hot Dog Contest 2014" for 0:10:30 later at 2020-12-31 06:56:07.332021+00:00
tubesync         | 2020-12-31T06:45:37.362685274Z Rescheduling Downloading media for "Crash Course Surveys"
tubesync         | 2020-12-31T06:45:37.362736361Z Traceback (most recent call last):
tubesync         | 2020-12-31T06:45:37.362745709Z   File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
tubesync         | 2020-12-31T06:45:37.362756157Z     func(*args, **kwargs)
tubesync         | 2020-12-31T06:45:37.362763633Z   File "/app/sync/tasks.py", line 285, in download_media
tubesync         | 2020-12-31T06:45:37.362771441Z     filepath = media.filepath
tubesync         | 2020-12-31T06:45:37.362778364Z   File "/app/sync/models.py", line 1043, in filepath
tubesync         | 2020-12-31T06:45:37.362786675Z     return self.source.directory_path / self.filename
tubesync         | 2020-12-31T06:45:37.362793510Z   File "/app/sync/models.py", line 1010, in filename
tubesync         | 2020-12-31T06:45:37.362800527Z     media_details = self.format_dict
tubesync         | 2020-12-31T06:45:37.362807322Z   File "/app/sync/models.py", line 879, in format_dict
tubesync         | 2020-12-31T06:45:37.362815939Z     display_format = self.get_display_format(format_str)
tubesync         | 2020-12-31T06:45:37.362822907Z   File "/app/sync/models.py", line 841, in get_display_format
tubesync         | 2020-12-31T06:45:37.362829974Z     acodec = aformat['acodec'].lower()
tubesync         | 2020-12-31T06:45:37.362836782Z TypeError: 'bool' object is not subscriptable
tubesync         | 2020-12-31T06:45:37.371240321Z Rescheduling task Downloading media for "Crash Course Surveys" for 0:10:30 later at 2020-12-31 06:56:07.371013+00:00
```

My settings for this channel are as follows:
![image](https://user-images.githubusercontent.com/17585204/103398386-c48fc280-4af9-11eb-8b26-0e5007a4e88b.png)

**Comment by meeb** [comment]
Thanks for the detailed bug report. Looks easily fixable so.
