### ISSUE TITLE
Can't Seem to add Alpharad Gold

### ISSUE THREAD

**Issue by KaiDevrim** [meeb/tubesync#314]
Hello! I have tried adding the Alpharad Gold youtube channel using the uploader id, `UC2gB7YCgfHIskI3HsY1teDw`, the uploader url, `https://www.youtube.com/channel/UC2gB7YCgfHIskI3HsY1teDw`, the channel handle, `@Alpharad-Gold` and the full url `https://www.youtube.com/@Alpharad-Gold` but none of these values seem to work. When I go into my tasks it just says it failed to extract_info and my docker logs say
```
2023-01-24 15:51:27,872 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
2023-01-24 15:51:27,873 [tubesync/ERROR] ERROR: [youtube:tab] UC2gB7YCgfHIskI3HsY1teDw: Unable to download API page: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Rescheduling Index media from source "AlpharadGold"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 162, in index_source_task
    videos = source.index_media()
  File "/app/sync/models.py", line 477, in index_media
    response = indexer(self.index_url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/c/UC2gB7YCgfHIskI3HsY1teDw/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
```

**Comment by KaiDevrim** [comment]
nvm needed to use the `youtube channel by id` option instead
