### ISSUE TITLE
"[Youtube] Unable to extract uploader id"

### ISSUE THREAD

**Issue by tamaskan** [meeb/tubesync#340]
https://github.com/yt-dlp/yt-dlp/issues/6247 needs updated yt-dlp

**Comment by meeb** [comment]
The bundled `yt-dlp` will be updated in the next release.

**Comment by kuhnchris** [comment]
I just fell over that aswell.

```

Rescheduling Downloading metadata for "2811cc2d-be3b-448f-be73-199bb91bb1e2"
Traceback (most recent call last):
  File "/home/kuhnchris/.local/share/virtualenvs/tubesync-l4jy0Bsy/lib/python3.10/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/home/kuhnchris/tubesync/tubesync/sync/tasks.py", line 230, in download_media_metadata
    metadata = media.index_metadata()
  File "/home/kuhnchris/tubesync/tubesync/sync/models.py", line 1348, in index_metadata
    return indexer(self.url)
  File "/home/kuhnchris/tubesync/tubesync/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=oZjRtD3kPnI": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "2811cc2d-be3b-448f-be73-199bb91bb1e2" for 0:00:06 later at 2023-02-19 22:40:53.940967+00:00
2023-02-19 22:40:51,899 [tubesync/DEBUG] [youtube] Extracting URL: https://www.youtube.com/watch?v=QiOc2E28TfQ
2023-02-19 22:40:51,899 [tubesync/DEBUG] [youtube] QiOc2E28TfQ: Downloading webpage
2023-02-19 22:40:52,446 [tubesync/DEBUG] [youtube] QiOc2E28TfQ: Downloading android player API JSON
2023-02-19 22:40:52,716 [tubesync/DEBUG] [youtube] QiOc2E28TfQ: Downloading MPD manifest
2023-02-19 22:40:53,006 [tubesync/ERROR] ERROR: [youtube] QiOc2E28TfQ: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

A quick `pip install yt-dlp --upgrade` fixed it.
i.e. it is fixed in upstream yt-dlp.
```
Installing collected packages: yt-dlp
  Attempting uninstall: yt-dlp
    Found existing installation: yt-dlp 2023.1.6
    Uninstalling yt-dlp-2023.1.6:
      Successfully uninstalled yt-dlp-2023.1.6
Successfully installed yt-dlp-2023.2.17
```

**Comment by meeb** [comment]
`yt-dlp` version `2023.02.17` is already bundled into the `:latest` image so this should be fixed with just a `docker pull`.
