### ISSUE TITLE
Fails to extract info for videos (nsig extraction failed)

### ISSUE THREAD

**Issue by abrazier** [meeb/tubesync#342]
Running :latest tag on unraid and everything was working up until 2 days ago. Looks like there was a phantomjs update to increase the timeout in the latest release of yt-dlp but not sure if that's the issue.

Current error I'm getting:

`2023-02-18 09:30:45,220 [tubesync/INFO] Scheduling task to download metadata for: https://www.youtube.com/watch?v=BDoGgGDa2J0
2023-02-18 09:30:50,019 [tubesync/DEBUG] [youtube] Extracting URL: https://www.youtube.com/watch?v=BDoGgGDa2J0
2023-02-18 09:30:50,020 [tubesync/DEBUG] [youtube] BDoGgGDa2J0: Downloading webpage
2023-02-18 09:30:50,693 [tubesync/DEBUG] [youtube] BDoGgGDa2J0: Downloading android player API JSON
2023-02-18 09:30:54,258 [tubesync/WARNING] [youtube] BDoGgGDa2J0: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = hyOShLlasWDs3cMH ; player = https://www.youtube.com/s/player/11e3a4ec/player_ias.vflset/en_US/base.js
2023-02-18 09:30:54,262 [tubesync/ERROR] ERROR: [youtube] BDoGgGDa2J0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Rescheduling Downloading metadata for "a4d68a2e-9e87-4033-bbf3-3d3ca26cd783"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1285, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '`

**Comment by abrazier** [comment]
Closing this issue as the update to v12.1 seems to have fixed the issue!

**Comment by meeb** [comment]
Yes this was an issue with YouTube which `yt-dlp` has been updated to resolve, this was "fixed" in tubesync just by pulling in the updated `yt-dlp`.
