### ISSUE TITLE
TypeError: db_type()

### ISSUE THREAD

**Issue by superjedi27** [meeb/tubesync#347]
Hello! Tubesync was working this morning(confirmed by downloaded media) then I updated and unraid was showing running but unhealthy, web interface wouldn't load, logs show this-

tried looking around a little bit but couldn't find any fixes, let me know if you need anything else

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
2023-02-20 09:46:30,029 [tubesync/INFO] Using database connection: django.db.backends.postgresql://tubesync:[hidden]@IP:PORT/tubesync
Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    main()
  File "/app/manage.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/base/schema.py", line 533, in add_field
    self.deferred_sql.extend(self._field_indexes_sql(model, field))
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/postgresql/schema.py", line 49, in _field_indexes_sql
    like_index_statement = self._create_like_index_sql(model, field)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/postgresql/schema.py", line 74, in _create_like_index_sql
    db_type = field.db_type(connection=self.connection)
TypeError: db_type() got an unexpected keyword argument 'connection'
s6-rc: warning: unable to start service tubesync-init: command exited 1
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:

**Comment by meeb** [comment]
Thanks for reporting, this should be fixed in `:latest` once the image builds.

@kuhnchris seems the postgresql backend explicitly passes the `connection` as a kwarg and not an arg which is different to SQLite and MySQL. Mentioning for you reference.
