### ISSUE TITLE
Unable to extract uploader id. No meta data returned by youtube-dl.

### ISSUE THREAD

**Issue by ShadowfootNZ** [meeb/tubesync#351]
I am consistently getting an error with downloaded. I noticed it first with my my Watch Later list. The following is what I think is all the pieces of the log for one item. 
I have previously been getting items from this list. 
I'm using docker and postgres. wiped the container and restarted it. (The latest attempt was today.) I'm using _ghcr.io/meeb/tubesync:latest_
The most recent successful download was 11 days ago, on another source. 

I recently changed from using Chrome to using Firefox. Could this be a cookies issue? My cookies.txt file is being updated by tubesync or related. Nothing else is touching it. 

```
2023-03-01 18:03:11,302 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-03-01 18:03:11,361 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-03-01 18:03:11,371 [tubesync/DEBUG] [youtube] sfDSbR3UvtY: Downloading webpage
2023-03-01 18:03:11,424 [tubesync/DEBUG] [youtube] xN9Ohfnp_4s: Downloading webpage
2023-03-01 18:03:11,453 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-03-01 18:03:11,510 [tubesync/DEBUG] [youtube] znulbnRynOc: Downloading webpage
2023-03-01 18:03:12,313 [tubesync/DEBUG] [youtube] sfDSbR3UvtY: Downloading android player API JSON
2023-03-01 18:03:12,693 [tubesync/DEBUG] [youtube] znulbnRynOc: Downloading android player API JSON
2023-03-01 18:03:12,706 [tubesync/DEBUG] [youtube] xN9Ohfnp_4s: Downloading android player API JSON
2023-03-01 18:03:12,944 [tubesync/ERROR] ERROR: [youtube] sfDSbR3UvtY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Rescheduling Downloading metadata for "02d0df46-b831-4102-816d-3d598d2d115d"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=sfDSbR3UvtY": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "02d0df46-b831-4102-816d-3d598d2d115d" for 0:40:06 later at 2023-03-01 05:43:18.954144+00:00
```

I've added a new source, and it, too is having errors.

```
2023-03-01 18:47:37,114 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-03-01 18:47:37,181 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-03-01 18:47:37,193 [tubesync/DEBUG] [youtube] lisncxkbHfc: Downloading webpage
2023-03-01 18:47:37,260 [tubesync/DEBUG] [youtube] oh_1c4NFnk4: Downloading webpage
2023-03-01 18:47:37,265 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-03-01 18:47:37,342 [tubesync/DEBUG] [youtube] fcoNym1Q1Ds: Downloading webpage
2023-03-01 18:47:38,161 [tubesync/DEBUG] [youtube] oh_1c4NFnk4: Downloading android player API JSON
2023-03-01 18:47:38,223 [tubesync/DEBUG] [youtube] lisncxkbHfc: Downloading android player API JSON
2023-03-01 18:47:38,305 [tubesync/DEBUG] [youtube] fcoNym1Q1Ds: Downloading android player API JSON
2023-03-01 18:47:38,583 [tubesync/ERROR] ERROR: [youtube] oh_1c4NFnk4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Rescheduling Downloading metadata for "520909e9-a9d3-4014-9834-5a4db05eb60e"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=oh_1c4NFnk4": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "520909e9-a9d3-4014-9834-5a4db05eb60e" for 0:00:21 later at 2023-03-01 05:47:59.594683+00:00
2023-03-01 18:47:38,676 [tubesync/ERROR] ERROR: [youtube] lisncxkbHfc: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Rescheduling Downloading metadata for "242a0b70-4f86-4860-9373-31a3aef7cea2"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=lisncxkbHfc": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "242a0b70-4f86-4860-9373-31a3aef7cea2" for 0:00:21 later at 2023-03-01 05:47:59.683989+00:00
2023-03-01 18:47:38,721 [tubesync/ERROR] ERROR: [youtube] fcoNym1Q1Ds: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Rescheduling Downloading metadata for "8d5894a8-37ac-4778-9d52-f11d56f482b6"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 227, in download_media_metadata
    metadata = media.index_metadata()
  File "/app/sync/models.py", line 1267, in index_metadata
    return indexer(self.url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=fcoNym1Q1Ds": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "8d5894a8-37ac-4778-9d52-f11d56f482b6" for 0:00:21 later at 2023-03-01 05:47:59.729879+00:0
```

**Comment by meeb** [comment]
What version of tubesync and `yt-dlp` are you running?

**Comment by ShadowfootNZ** [comment]
Sorry for the delay. I'm on **TubeSync** version _0.11.0_ with **yt-dlp** version _2022.09.01_ and **FFmpeg** version _4.3.4-0+deb11u1._
Is there something I can do to get the yt-dlp 2023-92-17? I had hoped using a new instance in docker with _ghcr.io/meeb/tubesync:latest_ would have picked up the best available versions.

**Comment by meeb** [comment]
Your issues are because you're running an old version. `ghcr.io/meeb/tubesync:latest` contains the fixes you need so just pull that.

**Comment by ShadowfootNZ** [comment]
Thanks. I see I had the following docker images, and it looks like it was running the older one.
REPOSITORY              TAG       IMAGE ID       CREATED        SIZE
ghcr.io/meeb/tubesync   latest    249320e9f76d   9 days ago     538MB
ghcr.io/meeb/tubesync   <none>    3eebe68df551   5 months ago   679MB

I don't know why it wasn't using the newer version. I've blown away both and forced a new download. I'm now on TubeSync version 0.12.1 with yt-dlp version 2023.02.17 and FFmpeg version N-109874-gaeceefa622-20230217 and things are working as expected. 

This issue can be closed.
