### ISSUE TITLE
Indexing media fails without metadata

### ISSUE THREAD

**Issue by Adam-Gibbs** [meeb/tubesync#366]
Trying to index a new source, from a fresh install and this is the error I am seeing in the GUI:
![image](https://user-images.githubusercontent.com/41566831/229291480-7f824383-31c7-479c-ab96-db1cd8aec409.png)

Settings I used:
![image](https://user-images.githubusercontent.com/41566831/229291507-3b9d8e1a-3d13-479b-9563-d6d215853cd6.png)

Logs
```
192.168.1.252 - - [01/Apr/2023:14:12:26 +0100] "GET /tasks?message=reset HTTP/1.1" 200 2811 "http://192.168.1.224/tasks-reset" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"
192.168.1.252 - - [01/Apr/2023:14:12:26 +0100] "GET /static/styles/tubesync.css HTTP/1.1" 200 34554 "http://192.168.1.224/tasks?message=reset" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"
2023-04-01 14:15:03,500 [tubesync/DEBUG] [youtube:tab] Extracting URL: https://www.youtube.com/c/@BrightSunTravels/videos
2023-04-01 14:15:03,508 [tubesync/DEBUG] [youtube:tab] @BrightSunTravels/videos: Downloading webpage
2023-04-01 14:15:03,624 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (1/3)...
2023-04-01 14:15:03,624 [tubesync/DEBUG] [youtube:tab] @BrightSunTravels/videos: Downloading webpage
2023-04-01 14:15:03,752 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (2/3)...
2023-04-01 14:15:03,752 [tubesync/DEBUG] [youtube:tab] @BrightSunTravels/videos: Downloading webpage
2023-04-01 14:15:03,855 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (3/3)...
2023-04-01 14:15:03,855 [tubesync/DEBUG] [youtube:tab] @BrightSunTravels/videos: Downloading webpage
2023-04-01 14:15:03,968 [tubesync/WARNING] [youtube:tab] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
2023-04-01 14:15:03,969 [tubesync/DEBUG] [youtube:tab] @BrightSunTravels/videos: Downloading API parameters API JSON
2023-04-01 14:15:04,078 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
2023-04-01 14:15:04,078 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (1/3)...
2023-04-01 14:15:04,079 [tubesync/DEBUG] [youtube:tab] @BrightSunTravels/videos: Downloading API parameters API JSON
2023-04-01 14:15:04,180 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
2023-04-01 14:15:04,180 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (2/3)...
2023-04-01 14:15:04,180 [tubesync/DEBUG] [youtube:tab] @BrightSunTravels/videos: Downloading API parameters API JSON
2023-04-01 14:15:04,303 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
2023-04-01 14:15:04,303 [tubesync/WARNING] [youtube:tab] HTTP Error 404: Not Found. Retrying (3/3)...
2023-04-01 14:15:04,304 [tubesync/DEBUG] [youtube:tab] @BrightSunTravels/videos: Downloading API parameters API JSON
2023-04-01 14:15:04,398 [tubesync/WARNING] [youtube:tab] YouTube said: ERROR - Requested entity was not found.
2023-04-01 14:15:04,399 [tubesync/ERROR] ERROR: [youtube:tab] @BrightSunTravels: Unable to download API page: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Rescheduling Index media from source "brightsuntravels"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 161, in index_source_task
    videos = source.index_media()
  File "/app/sync/models.py", line 517, in index_media
    response = indexer(self.index_url)
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/c/@BrightSunTravels/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Index media from source "brightsuntravels" for 0:10:30 later at 2023-04-01 13:25:34.408398+00:00
```

**Comment by meeb** [comment]
That's because `@BrightSunTravels` is not a YouTube channel name. The actual channel name is https://www.youtube.com/channel/UCHudN_9O_OD5KQIueahpYvg - add a new source by channel ID and enter `UCHudN_9O_OD5KQIueahpYvg` as the ID.

This is also discussed in #299 and #243

**Comment by Adam-Gibbs** [comment]
Thank you, for you help that has fixed the issue
