### ISSUE TITLE
NoneType object error when indexing media

### ISSUE THREAD

**Issue by davidancalagon** [meeb/tubesync#382]
Seems after the last upgrade to my docker image, I'm getting the following error when it attempts to index media for several of my sources:

Index media from source <source name>, attempted 1 time
Error: "'NoneType' object has no attribute 'get'"
Task will be retried at <date and time>

It will attempt a retry, and then fail with the same error.  This appears to be happening only with some sources, and each source has been checked to verify it still exists on the website.

Thanks in advance for the help.

**Comment by meeb** [comment]
Can you look in your container logs and paste the full trace of the error? It'll be pretty hard to diagnose your issue from just that single line.

**Comment by davidancalagon** [comment]
Here's an example from the latest log entries:

2023-05-31T15:40:18.699278464Z Rescheduling Index media from source "<source redacted>"
2023-05-31T15:40:18.699322380Z Traceback (most recent call last):
2023-05-31T15:40:18.699373976Z   File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
2023-05-31T15:40:18.699423422Z     func(*args, **kwargs)
2023-05-31T15:40:18.699457398Z   File "/app/sync/tasks.py", line 173, in index_source_task
2023-05-31T15:40:18.699503536Z     key = video.get(source.key_field, None)
2023-05-31T15:40:18.699537283Z AttributeError: 'NoneType' object has no attribute 'get'
2023-05-31T15:40:18.706456568Z Rescheduling task Index media from source "<source redacted>" for 0:00:06 later at 2023-05-31 15:40:24.706179+00:00

**Comment by meeb** [comment]
That seems to be an issue with `yt-dlp` indexing YouTube. Can you provide a channel where this isn't working?

**Comment by davidancalagon** [comment]
The 8-Bit Guy is one of the channels in question.  https://www.youtube.com/@The8BitGuy

**Comment by meeb** [comment]
https://www.youtube.com/@The8BitGuy isn't technically a channel, the actual channel for that is https://www.youtube.com/channel/UC8uT9cgJorJPWu7ITLGo9Ww. Try adding the channel by ID and use that URL instead.

**Comment by davidancalagon** [comment]
Sorry, I have it correct in TubeSync.  I actually went to youtube.com to get the channel url I gave you, but in TubeSync it's referenced by the channel key (UC8uT9cgJorJPWu7ITLGo9Ww).

**Comment by meeb** [comment]
OK. This still doesn't make a lot of sense. What this error means is where `yt-dlp` should be returning something like `[{... dict of video data ...}, {... dict of video data ...},  ... ]` it's actually returning something like `[None, None, ...]`.

Does this command return a big dict of data to the terminal for you?

`docker exec -ti tubesync python3 /app/manage.py youtube-dl-info https://www.youtube.com/channel/UC8uT9cgJorJPWu7ITLGo9Ww`

**Comment by davidancalagon** [comment]
It appears I'm getting a lot of failures in name resolution:

# python3 /app/manage.py youtube-dl-info https://www.youtube.com/channel/UC8uT9cgJorJPWu7ITLGo9Ww
2023-05-31 12:59:55,597 [tubesync/INFO] Using database connection: django.db.backends.mysql://squatgiant:[hidden]@10.253.78.254:33306/tubesync
Showing information for URL: https://www.youtube.com/channel/UC8uT9cgJorJPWu7ITLGo9Ww
2023-05-31 12:59:56,445 [tubesync/DEBUG] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UC8uT9cgJorJPWu7ITLGo9Ww
2023-05-31 12:59:56,446 [tubesync/DEBUG] [youtube:tab] UC8uT9cgJorJPWu7ITLGo9Ww: Downloading webpage
2023-05-31 13:00:16,465 [tubesync/WARNING] [youtube:tab] <urlopen error [Errno -3] Temporary failure in name resolution>. Retrying (1/3)...
2023-05-31 13:00:16,465 [tubesync/DEBUG] [youtube:tab] UC8uT9cgJorJPWu7ITLGo9Ww: Downloading webpage
2023-05-31 13:00:36,484 [tubesync/WARNING] [youtube:tab] <urlopen error [Errno -3] Temporary failure in name resolution>. Retrying (2/3)...
2023-05-31 13:00:36,484 [tubesync/DEBUG] [youtube:tab] UC8uT9cgJorJPWu7ITLGo9Ww: Downloading webpage
2023-05-31 13:00:56,505 [tubesync/WARNING] [youtube:tab] <urlopen error [Errno -3] Temporary failure in name resolution>. Retrying (3/3)...
2023-05-31 13:00:56,506 [tubesync/DEBUG] [youtube:tab] UC8uT9cgJorJPWu7ITLGo9Ww: Downloading webpage
2023-05-31 13:01:16,526 [tubesync/WARNING] [youtube:tab] Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution'))). Giving up after 3 retries
2023-05-31 13:01:16,531 [tubesync/DEBUG] [youtube:tab] UC8uT9cgJorJPWu7ITLGo9Ww: Downloading API parameters API JSON
2023-05-31 13:01:36,553 [tubesync/WARNING] [youtube:tab] <urlopen error [Errno -3] Temporary failure in name resolution>. Retrying (1/3)...
2023-05-31 13:01:36,555 [tubesync/DEBUG] [youtube:tab] UC8uT9cgJorJPWu7ITLGo9Ww: Downloading API parameters API JSON

However, it's only happening for some channels, and when I check the query log for my DNS server, it shows the query for youtube.com coming through and the correct resolver information being returned.

**Comment by meeb** [comment]
That makes more sense. I'd very much go with a network issue then rather than a code issue. Perhaps an IPv6 problem?

**Comment by davidancalagon** [comment]
Not sure.  I'll investigate.  If you don't hear from me on this matter again, consider it my screw-up ;)

**Comment by meeb** [comment]
What was it in the end? While this wasn't an issue directly with tubesync I can probably add a better failure mode and error messages for other people who encounter this.
