### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int' when indexing and downloading videos

### ISSUE THREAD

**Issue by Merlinux-source** [meeb/tubesync#386]
```
2023-06-28 19:50:24,601 [tubesync/DEBUG] [youtube] Extracting URL: https://www.youtube.com/watch?v=JjQDik3yNhA
2023-06-28 19:50:24,601 [tubesync/DEBUG] [youtube] JjQDik3yNhA: Downloading webpage
2023-06-28 19:50:25,174 [tubesync/DEBUG] [youtube] JjQDik3yNhA: Downloading ios player API JSON
2023-06-28 19:50:25,336 [tubesync/DEBUG] [youtube] JjQDik3yNhA: Downloading android player API JSON
2023-06-28 19:50:25,520 [tubesync/DEBUG] [youtube] JjQDik3yNhA: Downloading m3u8 information
2023-06-28 19:50:25,997 [tubesync/INFO] Media: Mental Outlaw / JjQDik3yNhA has a valid publishing date, marking to be unskipped
Rescheduling Downloading metadata for "b6b267a4-02ec-4a86-99af-34f7f9b896ca"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 265, in download_media_metadata
    media.save()
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.11/dist-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
           ^
  File "/usr/local/lib/python3.11/dist-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/signals.py", line 140, in media_post_save
    if instance.get_format_str():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/models.py", line 846, in get_format_str
    audio_match, audio_format = self.get_best_audio_format()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/models.py", line 824, in get_best_audio_format
    return get_best_audio_format(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/matching.py", line 57, in get_best_audio_format
    audio_formats = list(reversed(sorted(audio_formats, key=lambda k: k['abr'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
Rescheduling task Downloading metadata for "b6b267a4-02ec-4a86-99af-34f7f9b896ca" for 0:00:21 later at 2023-06-28 18:50:47.164258+00:00
```
Hi, I just setup tubesync for the first time in a docker container and because I was expecting downloads to happen much quicker (in my case just starting the downloads) I looked at the log files and saw these log entrys
I looked at some issues that might be related to this and didn't find anything similar.
because I'm a new user of this software I can't tell if this is normal behavior or not.
the container runs for about two hours at the point of writing and still hasn't downloaded a single video
here are the metrics from the dashboard
![Screenshot TubeSync - Dashboard](https://github.com/meeb/tubesync/assets/67962212/f5b8be2f-2630-48cf-9f8b-1a453ae54427)
I looked briefly at the code that might be causing this behaviour (sync/matching.py line 57) and can't find a direct corolation except that maybe yt-dl is having trouble getting the expected data.
Thank you in advance!

**Comment by meeb** [comment]
That error looks like yt-dlp failed to extract any audio streams for that video. What are your settings for the source that video is from?

**Comment by Merlinux-source** [comment]
It's basicly the default as you can see here
![Screenshot TubeSync - Dashboard](https://github.com/meeb/tubesync/assets/67962212/427b42f2-32bf-4344-ba1d-2a564a6e6032)
do you mean that no audio stream was found or that no matching audio streams were found?

**Comment by meeb** [comment]
Can you paste the format match table from that media items overview page? Your error seems to be that one or more of the audio formats passed to the matching function is or contains a None, which isn't sort-able. Either this is an issue with the metadata changing format or an issue to do a difference in metadata parsing in the latest build.

**Comment by Merlinux-source** [comment]
do you mean like this?
```


Source | Mental Outlaw
-- | --
Duration | 00:08:20
Desired format | 1080p (video:VP9, audio:MP4A) 60FPS
Fallback | Get next best resolution but at least HD
Downloaded? |  
Can download? |  
Available formats | ID: sb2                                                                                     ID: sb1                                                                                     ID: sb0                                                                                     ID: 249-drc                          , audio:opus @51.074k / 48000Hz                                                           ID: 250-drc                          , audio:opus @67.67k / 48000Hz                                                           ID: 249                          , audio:opus @50.875k / 48000Hz                                                           ID: 250                          , audio:opus @67.541k / 48000Hz                                                           ID: 140-drc                          , audio:mp4a.40.2 @129.491k / 44100Hz             (matched)                                              ID: 251-drc                          , audio:opus @128.094k / 48000Hz                                                           ID: 140                          , audio:mp4a.40.2 @129.488k / 44100Hz                                                           ID: 251                          , audio:opus @127.856k / 48000Hz                                                           ID: 394             , 144p (256x144), fps:30, video:av01.0.00M.08 @27.831k                                                                        ID: 160             , 144p (256x144), fps:30, video:avc1.4d400c @17.523k                                                                        ID: 278             , 144p (256x144), fps:30, video:vp9 @35.002k                                                                        ID: 395             , 240p (426x240), fps:30, video:av01.0.00M.08 @43.019k                                                                        ID: 133             , 240p (426x240), fps:30, video:avc1.4d4015 @29.614k                                                                        ID: 242             , 240p (426x240), fps:30, video:vp9 @51.749k                                                                        ID: 396             , 360p (640x360), fps:30, video:av01.0.01M.08 @75.116k                                                                        ID: 134             , 360p (640x360), fps:30, video:avc1.4d401e @49.015k                                                                        ID: 18             , 360p (640x360), fps:30, video:avc1.42001E @218.098k             , audio:mp4a.40.2 @Nonek / 44100Hz                                                           ID: 243             , 360p (640x360), fps:30, video:vp9 @91.203k                                                                        ID: 397             , 480p (854x480), fps:30, video:av01.0.04M.08 @129.738k                                                                        ID: 135             , 480p (854x480), fps:30, video:avc1.4d401f @65.476k                                                                        ID: 244             , 480p (854x480), fps:30, video:vp9 @129.738k                                                                        ID: 22             , 720p (1280x720), fps:30, video:avc1.64001F @335.383k             , audio:mp4a.40.2 @Nonek / 44100Hz                                                           ID: 136             , 720p (1280x720), fps:30, video:avc1.4d401f @206.562k                                                                        ID: 247             , 720p (1280x720), fps:30, video:vp9 @268.487k                                                                        ID: 398             , 720p60 (1280x720), fps:60, video:av01.0.08M.08 @323.109k                                                                        ID: 298             , 720p60 (1280x720), fps:60, video:avc1.4d4020 @124.113k                                                                        ID: 302             , 720p60 (1280x720), fps:60, video:vp9 @281.926k                                                                        ID: 399             , 1080p60 (1920x1080), fps:60, video:av01.0.09M.08 @673.839k                                                                        ID: 299             , 1080p60 (1920x1080), fps:60, video:avc1.64002a @400.44k                                                                        ID: 303             , 1080p60 (1920x1080), fps:60, video:vp9 @714.608k                          (matched)
Matched formats | Combined: no match           Audio: 140-drc (exact match)           Video: 303 (exact match)

Source 	[Mental Outlaw](http://localhost:4848/source/734430bb-29af-4426-b4d7-f0cbf11072f4)
Duration 	00:08:20
Desired format 	1080p (video:VP9, audio:MP4A) 60FPS
Fallback 	Get next best resolution but at least HD
Downloaded? 	
Can download? 	
Available formats 	
ID: sb2
ID: sb1
ID: sb0
ID: 249-drc , audio:opus @51.074k / 48000Hz
ID: 250-drc , audio:opus @67.67k / 48000Hz
ID: 249 , audio:opus @50.875k / 48000Hz
ID: 250 , audio:opus @67.541k / 48000Hz
ID: 140-drc , audio:mp4a.40.2 @129.491k / 44100Hz (matched)
ID: 251-drc , audio:opus @128.094k / 48000Hz
ID: 140 , audio:mp4a.40.2 @129.488k / 44100Hz
ID: 251 , audio:opus @127.856k / 48000Hz
ID: 394 , 144p (256x144), fps:30, video:av01.0.00M.08 @27.831k
ID: 160 , 144p (256x144), fps:30, video:avc1.4d400c @17.523k
ID: 278 , 144p (256x144), fps:30, video:vp9 @35.002k
ID: 395 , 240p (426x240), fps:30, video:av01.0.00M.08 @43.019k
ID: 133 , 240p (426x240), fps:30, video:avc1.4d4015 @29.614k
ID: 242 , 240p (426x240), fps:30, video:vp9 @51.749k
ID: 396 , 360p (640x360), fps:30, video:av01.0.01M.08 @75.116k
ID: 134 , 360p (640x360), fps:30, video:avc1.4d401e @49.015k
ID: 18 , 360p (640x360), fps:30, video:avc1.42001E @218.098k , audio:mp4a.40.2 @Nonek / 44100Hz
ID: 243 , 360p (640x360), fps:30, video:vp9 @91.203k
ID: 397 , 480p (854x480), fps:30, video:av01.0.04M.08 @129.738k
ID: 135 , 480p (854x480), fps:30, video:avc1.4d401f @65.476k
ID: 244 , 480p (854x480), fps:30, video:vp9 @129.738k
ID: 22 , 720p (1280x720), fps:30, video:avc1.64001F @335.383k , audio:mp4a.40.2 @Nonek / 44100Hz
ID: 136 , 720p (1280x720), fps:30, video:avc1.4d401f @206.562k
ID: 247 , 720p (1280x720), fps:30, video:vp9 @268.487k
ID: 398 , 720p60 (1280x720), fps:60, video:av01.0.08M.08 @323.109k
ID: 298 , 720p60 (1280x720), fps:60, video:avc1.4d4020 @124.113k
ID: 302 , 720p60 (1280x720), fps:60, video:vp9 @281.926k
ID: 399 , 1080p60 (1920x1080), fps:60, video:av01.0.09M.08 @673.839k
ID: 299 , 1080p60 (1920x1080), fps:60, video:avc1.64002a @400.44k
ID: 303 , 1080p60 (1920x1080), fps:60, video:vp9 @714.608k (matched)
Matched formats 	Combined: no match
Audio: 140-drc (exact match)
Video: 303 (exact match)
```

**Comment by meeb** [comment]
Yep, thanks. All run the metadata for that video through a test or two when I get a moment to see what the issue is.

**Comment by davidkylenz** [comment]
I see the same error for 4 sources so far, I select MP4A audio for all sources.

![IMG_1388](https://github.com/meeb/tubesync/assets/14541588/3354b28a-32db-403e-8ba4-af7bb976e0b3)
![IMG_1389](https://github.com/meeb/tubesync/assets/14541588/ba9acac0-2016-4b3f-a3aa-6dcd4120b7e3)

**Comment by davidancalagon** [comment]
I'm having this issue with a source set to OPUS for audio format.

**Comment by meeb** [comment]
Once the container is built in about 20-30 minutes this should be resolved once you pull the latest container. It seems there's now some media formats which do not have audio or video codecs (storyboards or something whatever they are?) which were not being handled properly. The above patch ignores them.
