### ISSUE TITLE
invalid Netscape format cookies file

### ISSUE THREAD

**Issue by goose-ws** [meeb/tubesync#395]
I recently decided to add a cookie so I can pull videos from my "Liked videos" playlist. I grabbed it via [Cookie Quick Manager](https://github.com/ysard/cookie-quick-manager) for Firefox, and exported by `youtube.com` cookie in Netscape format.

To censor the sensitive information, here's the `cookies.txt`

```
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com    false   /       true    1690414695      GPS     1
.youtube.com    false   /       true    0       YSC     ███████████
.youtube.com    false   /       true    1705964895      VISITOR_INFO1_LIVE      ███████████
.youtube.com    false   /       true    1721950304      __Secure-1PSIDTS        ██████████████████████████████████████████████████████████████████████████████
.youtube.com    false   /       true    1721950304      __Secure-3PSIDTS        ██████████████████████████████████████████████████████████████████████████████
.youtube.com    false   /       false   1753486304      HSID    █████████████████
.youtube.com    false   /       true    1753486304      SSID    █████████████████
.youtube.com    false   /       false   1753486304      APISID  ██████████████████████████████████
.youtube.com    false   /       true    1753486304      SAPISID ██████████████████████████████████
.youtube.com    false   /       true    1753486304      __Secure-1PAPISID       ██████████████████████████████████
.youtube.com    false   /       true    1753486304      __Secure-3PAPISID       ██████████████████████████████████
.youtube.com    false   /       false   1753486304      SID     ███████████████████████████████████████████████████████████████████████
.youtube.com    false   /       true    1753486304      __Secure-1PSID  ███████████████████████████████████████████████████████████████████████
.youtube.com    false   /       true    1753486304      __Secure-3PSID  ███████████████████████████████████████████████████████████████████████
.youtube.com    false   /       true    1753486304      LOGIN_INFO      ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
.youtube.com    false   /       false   1690414584      ST-1█████l      ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
.youtube.com    false   /       true    1753486966      PREF    tz=America.New_York&f5=30000
.youtube.com    false   /       false   1721950970      SIDCC   ██████████████████████████████████████████████████████████████████████████
.youtube.com    false   /       true    1721950970      __Secure-1PSIDCC        ███████████████████████████████████████████████████████████████████████████
.youtube.com    false   /       true    1721950970      __Secure-3PSIDCC        ██████████████████████████████████████████████████████████████████████████
```

But when I run Tubesync, I get the output:

```
2023-07-26 19:47:56,128 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
/usr/lib/python3.11/http/cookiejar.py:2083: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "/usr/lib/python3.11/http/cookiejar.py", line 2056, in _really_load
    assert domain_specified == initial_dot
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

  _warn_unhandled_exception()
Rescheduling Index media from source "Liked Videos"
Traceback (most recent call last):
  File "/usr/lib/python3.11/http/cookiejar.py", line 2056, in _really_load
    assert domain_specified == initial_dot
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 159, in index_source_task
    videos = source.index_media()
             ^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/models.py", line 517, in index_media
    response = indexer(self.index_url)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/youtube.py", line 54, in get_media_info
    with yt_dlp.YoutubeDL(opts) as y:
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yt_dlp/YoutubeDL.py", line 767, in __init__
    self._setup_opener()
  File "/usr/local/lib/python3.11/dist-packages/yt_dlp/YoutubeDL.py", line 3997, in _setup_opener
    self.cookiejar = load_cookies(opts_cookiefile, opts_cookiesfrombrowser, self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yt_dlp/cookies.py", line 115, in load_cookies
    jar.load(ignore_discard=True, ignore_expires=True)
  File "/usr/local/lib/python3.11/dist-packages/yt_dlp/cookies.py", line 1308, in load
    self._really_load(cf, filename, ignore_discard, ignore_expires)
  File "/usr/lib/python3.11/http/cookiejar.py", line 2084, in _really_load
    raise LoadError("invalid Netscape format cookies file %r: %r" %
http.cookiejar.LoadError: invalid Netscape format cookies file '/config/cookies.txt': '.youtube.com\tfalse\t/\ttrue\t1690414695\tGPS\t1'
```

If I replace all the tab characters with spaces, I the `http.cookiejar.LoadError:` error changes:

```
http.cookiejar.LoadError: '/config/cookies.txt' does not look like a Netscape format cookies file
```

I don't think my format is wrong, but perhaps it is? Is there a better extension to export the cookie with?

**Comment by goose-ws** [comment]
For anyone who comes across this, I used `curl` to rewrite the cookie, which solved the problem for me:

```
curl -b cookie_broken.txt --cookie-jar cookies.txt https://www.youtube.com
```

**Comment by meeb** [comment]
Thanks for the issue and note on how you solved this. I can only assume that your browser plugin doesn't export cookies in a totally Netscape compatible format, or that `http.cookiejar` is very fussy.
