### ISSUE TITLE
Failed to download media to disk, expected outfile does not exist.

### ISSUE THREAD

**Issue by hwcopeland** [meeb/tubesync#403]
I've searched through quite a few threads and decided to finally open an issue. It seems others have had similar issues however i still cant figure out what is going on. Media is being downloaded direct to a nfs mount to Truenas.

```2023-08-22 21:42:08,282 [tubesync/INFO] Downloading media: KXi-CV--Wq0 (UUID: b02bfd4e-eeca-4f7b-83b6-aa36841d0ca0) to: "/downloads/video/whistlindiesel/whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].mkv"
2023-08-22 21:42:09,601 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 0.1% of N/A at 2.84MiB/s, 06:40 remaining
2023-08-22 21:42:11,132 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 0.9% of N/A at 114.16KiB/s, 03:32 remaining
2023-08-22 21:42:12,381 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 1.8% of N/A at 6.58MiB/s, 02:44 remaining
2023-08-22 21:42:12,857 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 1.8% of N/A at 2.10MiB/s, 03:12 remaining
2023-08-22 21:42:14,302 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 2.6% of N/A at 94.14KiB/s, 03:06 remaining
2023-08-22 21:42:15,495 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 3.5% of N/A at 6.57MiB/s, 02:47 remaining
2023-08-22 21:42:16,023 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 3.6% of N/A at 1.89MiB/s, 03:01 remaining
2023-08-22 21:42:17,480 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 4.4% of N/A at 96.10KiB/s, 02:59 remaining
2023-08-22 21:42:18,798 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 5.3% of N/A at 6.09MiB/s, 02:46 remaining
2023-08-22 21:42:19,236 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 5.4% of N/A at 2.28MiB/s, 02:56 remaining
2023-08-22 21:42:20,728 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 6.1% of N/A at 107.39KiB/s, 02:55 remaining
2023-08-22 21:42:22,053 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 7.0% of N/A at 6.20MiB/s, 02:46 remaining
2023-08-22 21:42:22,553 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 7.1% of N/A at 2.00MiB/s, 02:53 remaining
2023-08-22 21:42:23,995 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 7.9% of N/A at 96.33KiB/s, 02:51 remaining
2023-08-22 21:42:25,291 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 8.8% of N/A at 6.18MiB/s, 02:44 remaining
2023-08-22 21:42:25,707 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 8.9% of N/A at 2.40MiB/s, 02:49 remaining
2023-08-22 21:42:34,723 [tubesync/INFO] [youtube-dl] finished downloading: whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].f313.webm - 110.00MiB in 00:00:25
[download] Got error: HTTP Error 403: Forbidden
ERROR: fragment 1 not found, unable to continue
2023-08-22 21:42:34,899 [tubesync/ERROR] Failed to download media: KXi-CV--Wq0 (UUID: b02bfd4e-eeca-4f7b-83b6-aa36841d0ca0) to disk, expected outfile does not exist: /downloads/video/whistlindiesel/whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].mkv
Rescheduling Downloading media for "The Fastest Way to Lose Half a Million Dollars. My Ferrari is Gone."
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 407, in download_media
    raise DownloadFailedException(err)
common.errors.DownloadFailedException: Failed to download media: KXi-CV--Wq0 (UUID: b02bfd4e-eeca-4f7b-83b6-aa36841d0ca0) to disk, expected outfile does not exist: /downloads/video/whistlindiesel/whistlindiesel - 2023-08-18 - the-fastest-way-to-lose-half-a-million-dollars-my-ferrari-is-gone [KXi-CV--Wq0] [2160p-vp9-mp4a].mkv
Rescheduling task Downloading media for "The Fastest Way to Lose Half a Million Dollars. My Ferrari is Gone." for 0:00:06 later at 2023-08-23 02:42:40.904070+00:00
2023-08-22 21:42:38,432 [tubesync/INFO] Downloading media: Wt2gNJh5bm4 (UUID: 9aaf5339-8fb6-42ce-99a3-0d07f82cb965) to: "/downloads/video/whistlindiesel/whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].mkv"
2023-08-22 21:42:39,994 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 0.1% of N/A at 3.00MiB/s, 03:46 remaining
2023-08-22 21:42:41,391 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 1.5% of N/A at 117.87KiB/s, 01:55 remaining
2023-08-22 21:42:42,635 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 2.9% of N/A at 6.64MiB/s, 01:30 remaining
2023-08-22 21:42:43,151 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 3.1% of N/A at 1.93MiB/s, 01:49 remaining
2023-08-22 21:42:44,740 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 4.4% of N/A at 99.72KiB/s, 01:49 remaining
2023-08-22 21:42:46,006 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 5.9% of N/A at 6.34MiB/s, 01:38 remaining
[download]   5.9% of ~ 680.00MiB at    3.77KiB/s ETA 01:42023-08-22 21:42:46,458 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 6.0% of N/A at 2.21MiB/s, 01:45 remaining
2023-08-22 21:42:47,853 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 7.4% of N/A at 98.47KiB/s, 01:43 remaining
2023-08-22 21:42:49,089 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 8.8% of N/A at 6.45MiB/s, 01:35 remaining
2023-08-22 21:42:49,452 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 9.0% of N/A at 2.74MiB/s, 01:39 remaining
2023-08-22 21:42:50,819 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 10.3% of N/A at 117.71KiB/s, 01:37 remaining
2023-08-22 21:42:52,233 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 11.8% of N/A at 5.96MiB/s, 01:31 remaining
2023-08-22 21:42:52,724 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 11.9% of N/A at 2.03MiB/s, 01:36 remaining
2023-08-22 21:42:54,123 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 13.2% of N/A at 114.33KiB/s, 01:34 remaining
2023-08-22 21:42:55,346 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 14.7% of N/A at 6.69MiB/s, 01:29 remaining
2023-08-22 21:42:55,849 [tubesync/INFO] [youtube-dl] downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 14.9% of N/A at 1.99MiB/s, 01:32 remaining
2023-08-22 21:43:02,620 [tubesync/INFO] [youtube-dl] finished downloading: whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].f313.webm - 110.00MiB in 00:00:22
[download] Got error: HTTP Error 403: Forbidden
ERROR: fragment 1 not found, unable to continue
2023-08-22 21:43:02,853 [tubesync/ERROR] Failed to download media: Wt2gNJh5bm4 (UUID: 9aaf5339-8fb6-42ce-99a3-0d07f82cb965) to disk, expected outfile does not exist: /downloads/video/whistlindiesel/whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].mkv
Rescheduling Downloading media for "Ferrari Durability Test #1 (incomplete)"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 407, in download_media
    raise DownloadFailedException(err)
common.errors.DownloadFailedException: Failed to download media: Wt2gNJh5bm4 (UUID: 9aaf5339-8fb6-42ce-99a3-0d07f82cb965) to disk, expected outfile does not exist: /downloads/video/whistlindiesel/whistlindiesel - 2023-08-15 - ferrari-durability-test-1-incomplete [Wt2gNJh5bm4] [2160p-vp9-mp4a].mkv
Rescheduling task Downloading media for "Ferrari Durability Test #1 (incomplete)" for 0:00:06 later at 2023-08-23 02:43:08.858701+00:00
2023-08-22 21:43:03,545 [tubesync/INFO] Downloading media: EdmOc6jna88 (UUID: 1f98947e-7872-47dc-8685-3ea48d59ca02) to: "/downloads/video/whistlindiesel/whistlindiesel - 2023-06-15 - testing-the-worlds-first-car-they-dont-make-them-like-they-used-to [EdmOc6jna88] [2160p-vp9-mp4a].mkv"```

**Comment by hwcopeland** [comment]
Similarity? 

https://www.reddit.com/r/youtubedl/comments/15tosxw/fragment_1_not_found/

Proposed solution:
Update yt-dl?

**Comment by meeb** [comment]
`yt-dlp` is up to date in the `:latest` tubesync image. That error is a generic catch-all error. Really all it means is "tubesync called yt-dlp to download a media item, and when the yt-dlp download completed the expected file didn't exist on disk". Obviously this could be caused by pretty much anything from yt-dlp being out of date to proxy issues, disk being full, permissions issues, youtube blocking your IP, basically any reason that would cause the download to fail. 

Given your logs show the download was attempted, it would imply that either the failure was merging the streams into a single container or with writing the final output file.

A reasonable test might be to drop a shell into the tubesync container and call `yt-dlp` from the command line, specifying the same requested formats, and see if that works.

**Comment by hwcopeland** [comment]
Well I didnt see this notification haha. 5 hours later I just submitted my first pull request and the issue was resolved once i tested it. Unknow if it was the true fix. testing could tell. However once the container was updated to my fork videos were downloading smooth and fast. #404

**Comment by hwcopeland** [comment]
Unneeded and unnecessary patch.

**Comment by meeb** [comment]
No problem, glad you got it resolved.
