### ISSUE TITLE
No metadata returned

### ISSUE THREAD

**Issue by Muerio** [meeb/tubesync#409]
Recently all my tasks started failing with the following error:
![image](https://github.com/meeb/tubesync/assets/11858860/27949330-1969-4a77-b8ee-2f24281f2ef8)

Is this something tubesync could fix or do we need to create an issue for yt-dlp?

**Comment by meeb** [comment]
Is there anything in the container logs for this error? That error is a wrapped error in tubesync which effectively just means "calling `yt-dlp` to get the metadata failed". It could be caused by pretty much anything, including network connection issues or YouTube blocking your IP etc. I don't think this is an issue with `yt-dlp` itself given I can index that channel without issue.

One test you can do is to check what `yt-dlp` is actually returning. If you are able, run the following command on the host machine you have tubesync installed on:

```bash
$ docker exec -ti tubesync python3 /app/manage.py youtube-dl-info "https://www.youtube.com/c/AbroadinJapan/videos"
```

If working, this should output a massive block of JSON to the terminal, if it's not working you should find out the actual error.

**Comment by shreram** [comment]
I ran into the same issue. I deleted the previous version of the cookies.txt file and downloaded the new version of cookies.txt (it has more content) and restarted tubesync container.  That fixed the issue.

@Muerio  Refer to this issue for more information
https://github.com/meeb/tubesync/issues/373

PS: I replaced actual playlistid with dummyplaylistid string
```code
docker exec -ti tubesync python3 /app/manage.py youtube-dl-info https://www.youtube.com/playlist?list=dummyplaylistid
Showing information for URL: https://www.youtube.com/playlist?list=dummyplaylistid
2023-09-16 09:04:40,598 [tubesync/INFO] [youtube-dl] using cookies.txt from: /config/cookies.txt
2023-09-16 09:04:40,765 [tubesync/DEBUG] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=dummyplaylistid
2023-09-16 09:04:40,766 [tubesync/DEBUG] [youtube:tab] dummyplaylistid: Downloading webpage
2023-09-16 09:04:41,107 [tubesync/WARNING] [youtube:tab] YouTube said: The playlist does not exist.
2023-09-16 09:04:41,126 [tubesync/ERROR] ERROR: [youtube:tab] dummyplaylistid: YouTube said: The playlist does not exist.
Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    main()
  File "/app/manage.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/management/commands/youtube-dl-info.py", line 17, in handle
    info = get_media_info(url)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/sync/youtube.py", line 60, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/playlist?list=dummyplaylistid": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
```
