### ISSUE TITLE
problem with mounted folders on raspbian

### ISSUE THREAD

**Issue by acaonweb** [meeb/tubesync#445]
Hi, 
I've created config and download folders as written in the guide, and everything works fine.
now if I mount them pointing to a network drive , I've permissions error.

I've mounted the folder using webmin, like the screenshot
![image](https://github.com/meeb/tubesync/assets/22882393/03012873-f0f8-4ed4-9bbb-0126689ec584)

the same for the download folder
Obvusly I can write and read the mounted folders
What can I do?

**Comment by acaonweb** [comment]
> Try changing the user ID and group ID your TubeSync container runs as to match whatever user and group can write to your network shares via the `PUID` and `PGID` container environment variables. This isn't specifically a TubeSync issue, but a general common running containers issue.

ok, so PUID=pi and PGID=pi ?

**Comment by meeb** [comment]
No, you need to specify user and group IDs as integers. As a user that can write to the network shares open a terminal and type `id`. You'll get something like:

```bash
uid=1001(pi) gid=1002(pi) groups=1001(pi)
```

And you would use (in the above example) `PUID=1001` and `GUID=1002`. They're the user and group IDs assigned to the account you want to use on your system.

**Comment by acaonweb** [comment]
oh lol sorry 😄😄 
I've made compose.yaml like that

<img width="641" alt="image" src="https://github.com/meeb/tubesync/assets/22882393/31da50c8-4f5c-419d-9f29-7406021865aa"> 

with 

<img width="380" alt="image" src="https://github.com/meeb/tubesync/assets/22882393/52dfd05a-e989-4896-ad83-7942f6f7e6ed">

the mounted folder like this

![image](https://github.com/meeb/tubesync/assets/22882393/4d3d2d37-ac5b-44b9-82f1-16062557009e)


and done 
`sudo docker compose up -d`

now:
<img width="914" alt="image" src="https://github.com/meeb/tubesync/assets/22882393/510f57ed-0765-438f-a07f-3f3a049a3eeb">

it's not running

and the log

`
pi@docker:~/dockercomposer $ sudo docker logs tubesync
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tubesync-init: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes
TUBESYNC_RESET_DOWNLOAD_DIR=True, Resetting /downloads directory permissions
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, sessions, sync
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/recorder.py", line 67, in ensure_schema
    with self.connection.schema_editor() as editor:
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/sqlite3/schema.py", line 36, in __exit__
    super().__exit__(exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/base/schema.py", line 120, in __exit__
    self.atomic.__exit__(exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.11/dist-packages/django/db/transaction.py", line 246, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.11/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/base/base.py", line 241, in _commit
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    main()
  File "/app/manage.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/executor.py", line 91, in migrate
    self.recorder.ensure_schema()
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
    raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (database is locked)
s6-rc: warning: unable to start service tubesync-init: command exited 1
`

**Comment by meeb** [comment]
Don't put the `config` directory on a network share, it stores an SQLite database and they do not work well on network shares (you get locking issues, like in your error logs). As for the downloads directory, do an:

```bash
sudo chown -R 1000:1000 /home/pi/Documents/MediaDownload
```

Your download dir is owned by root, which your normal user (with UID 1000) can't write to it.

**Comment by acaonweb** [comment]
DONE!!!!!
Thanks!!!!!!

**Comment by meeb** [comment]
No problem. These are generic Linux questions, but sure happy to help.
