### ISSUE TITLE
Handle "premium" streams properly

### ISSUE THREAD

**Issue by meeb** [meeb/tubesync#446]
Some media formats are now flagged as "premium" and require authentication and a subscription (such as cookies.txt exported from a YouTube account with a YouTube premium subscription) to access. Given it's likely a bad idea to use a YouTube premium account with TubeSync it would be a reasonable idea to ignore all premium streams entirely when selecting streams.

Currently, premium streams can be selected but then fail to download causing a permanent download failure for the media.

See #368 for some other peoples investigatory work into premium stream skipping for reference.

**Comment by ZTiKnl** [comment]
Hi, thanks for this amazing software and the excellent(!!!) support you provide on it here, many companies can (and should) learn from your example!
Now that the ass-kissing is out of the way... ;)

I have a couple of channels exhibiting similar behaviour as mentioned in the linked tickets, and am not entirely sure how to proceed here:

```
2024-04-02 21:30:55,491 [tubesync/INFO] Downloading media: BBWmRvIT0QY (UUID: a488ce03-4dd1-493f-8c2b-55b72cb3b2ee) to: "/downloads/video/taskmaster/Taskmaster (2020-03-25) - Task 2  #HomeTasking #StayHome [1080p] [vp09 opus].mkv"
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "BBWmRvIT0QY")
ERROR: [youtube] BBWmRvIT0QY: Requested format is not available. Use --list-formats for a list of available formats
2024-04-02 21:30:58,128 [tubesync/ERROR] Failed to download media: BBWmRvIT0QY (UUID: a488ce03-4dd1-493f-8c2b-55b72cb3b2ee) to disk, expected outfile does not exist: /downloads/video/taskmaster/Taskmaster (2020-03-25) - Task 2  #HomeTasking #StayHome [1080p] [vp09 opus].mkv
Rescheduling Downloading media for "Task 2 | #HomeTasking #StayHome"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 476, in download_media
    raise DownloadFailedException(err)
common.errors.DownloadFailedException: Failed to download media: BBWmRvIT0QY (UUID: a488ce03-4dd1-493f-8c2b-55b72cb3b2ee) to disk, expected outfile does not exist: /downloads/video/taskmaster/Taskmaster (2020-03-25) - Task 2  #HomeTasking #StayHome [1080p] [vp09 opus].mkv
Rescheduling task Downloading media for "Task 2 | #HomeTasking #StayHome" for 0:21:41 later at 2024-04-02 19:52:39.147573+00:00
```
Clicking on the errored task shows:
`Desired format | 1080p (video:VP9, audio:OPUS) 60FPS`
`Fallback | Get next best resolution or codec instead`
`Downloaded? Cross`
`Can download? Checkmark`
```
Matched formats:
-Combined: no match
-Audio: 251 (exact match)
-Video: 248 (fallback)
```

I am able to open this video on a webbrowser from the same ip-address, and it does not appear to be a premium video?
If it does help you, I can provide database files and/or complete log files, but didn't want to clutter this issue too much unless confirmed related first.
If not related, I'll gladly remove this comment and apologize for hijacking :x

**Comment by meeb** [comment]
@ZTiKnl I don't think this issue is related to premium streams, your issue looks to be an application block. Your tubesync instance requested https://www.youtube.com/watch?v=BBWmRvIT0QY however it received information on https://www.youtube.com/watch?v=aQvGIIdgFDM after a redirect. I'm not entirely sure what https://www.youtube.com/watch?v=aQvGIIdgFDM is - it appears to be a 5 minute video showing a not available with your application error, although I don't know why this would exist. It does seem to be an actual official YouTube video though at first glance.

As to why your tubesync instance gets redirected to an error page but the web browser works on the same IP I would assume the video you want to download is flagged to only work in a web browser and not on mobile devices. A lot of the time yt-dlp uses the data for mobile clients to download videos which would impersonate a mobile app.

I've not personally seen this behavior before. It's likely more something for yt-dlp to look at.

**Comment by ZTiKnl** [comment]
Oh wow, I did not notice that part at all....

I have removed my earlier comment to keep this issue free from clutter, and will investigate further before bothering the fine folks at yt-dlp too ;)

Thank you for your detailed reply!

**Comment by tcely** [comment]
@meeb What's the status on this? I think we are handling "premium" videos well enough and this can be closed.

**Comment by meeb** [comment]
Yep! Most likely, thanks. I'll close this for now. If anyone continues to have issues with premium streams please create a new issue.
