### ISSUE TITLE
Constantly running into 502 errors

### ISSUE THREAD

**Issue by kamtschatka** [meeb/tubesync#454]
I have set up tubesync to connect to an external database to improve performance and yet, when I am adding/deleting larger channels, I always get "502 bad gateway" errors.

Changing a single parameter fixes this issue and makes it work just fine: 
https://github.com/meeb/tubesync/blob/b11b667affcefaeb5eea8c762ba78f8774a84a4c/tubesync/tubesync/gunicorn.py#L25

Can this be updated to a more sensible value?

**Comment by meeb** [comment]
The issue here is not the time limit for gunicorn request execution it's that some actions which are slow on larger channels are processed in the active request and not offloaded to a background worker. Even if this was raised to 300 seconds or more there's still no assurance that absolutely massive channel update actions would complete in time. There are current efforts to rework this already underway. In the interim you can use some command line helpers to properly perform actions like deleting a large channel:

```bash
$ docker exec -ti tubesync python3 /app/manage.py delete-source [uuid of source here]
```

Of course if you want to increase the execution timeout in the interim as well you're welcome to do so, also note the nginx request has a timeout as well.

**Comment by Makr91** [comment]
Sorry to necro this, but I can't run the command line tool of this:

```
python3 ./manage.py reset-tasks
```
does not work for me, here is what I get

```
root@local-tubesync:/app# python3 ./manage.py reset-tasks
2024-05-10 22:55:55,672 [tubesync/INFO] Resettings all tasks...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: sync_source.delete_files_on_disk

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./manage.py", line 18, in <module>
    main()
  File "/app/./manage.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/management/commands/reset-tasks.py", line 20, in handle
    for source in Source.objects.all():
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: sync_source.delete_files_on_disk
```


When I run the Web Reset tasks, it actually deletes them, then starts to add them, I have tried to increase the time out. both in the nginx.conf

```
   fastcgi_read_timeout 900;
    proxy_connect_timeout 900s;
    proxy_send_timeout 900s;
    proxy_read_timeout 900s;
    client_body_timeout 900s;
    client_header_timeout 900s;
    send_timeout 900s;
    keepalive_timeout 900s;

```


and in the gunicorn.py
```
timeout = 3000

```


I am pretty patient person, so I am more than willing to wait for these processes to take a long time.


The problem I am having with the GUI is mentioned in many other issues, but I can't seem to get the command to run longer than 60 seconds even with all the settings I just mentioned being at 15 minutes or more (900 seconds)


I had 64 channels, added one, tried to delete it, it deleted the source, but then all the other subsequent tasks were "frozen". So I tried to reset the tasks via the GUI, and now I can't even do it via the CLI.

I think that if possible you should update documentation so that people don't accidentally use the UI to reset tasks. So they don't have to painstakingly recreate every single channel after curating their feed


Let me know if I can provide any more information to help, and I know there are plans to revamp this. So I am willing to help this along.


I am also not afraid of editing the SQL tables and columns, if its as easy as adding a column to a table, I can do that, but I am not very familiar with Gunicor and what exactly its trying to read/write from the tables for  this project.

**Comment by meeb** [comment]
Somehow your database schema is out of date and you're missing at least one column. A schema update runs automatically on container start so either you're not running tunesync in a container or you've done a database rollback or something? Try running:

`python3 manage.py migrate`

Then `reset-tasks` should work. Your error was:

`sqlite3.OperationalError: no such column: sync_source.delete_files_on_disk` which should be pretty self-explanatory.

**Comment by Makr91** [comment]
I am actually using https://github.com/jdeath/homeassistant-addons  repo for Home Assistant, with my own customizations.

It is indeed running in a container. I had went out of my way to add options to Jdeaths repo so that I can have it connect to the MariaDB Home Assistant Addon, since I was having more issues with sqllite (due to my Home Assistant disk i/o being overloaded, moving to an sql server on another Host, in a dedicated VM, solved my performance issues I was having. (I know I was asking too much of spinning rust to do all the add-ons I had installed))



But, doing what you said appears to have worked, All video sources are still showing up (thank --insert your holy deity here-- I didn't have to recreate all of them like I did 4 months ago), and all of the tasks are now slowly whittling away again.



Thank you

**Comment by meeb** [comment]
tubesync is built with Django so you can just use any Django database management commands with tubesync. Django manages the schema, including upgrades etc. for you and has extensive easy to read documentation if you're inclined to do things yourself. You can always create a backup of your sources with `manage.py dumpdata` as well. With the SQL errors like `no such column: sync_source.delete_files_on_disk` the database table name is `sync_source` and the missing column name was `delete_files_on_disk`. Good to hear it was easy to fix for you.

**Comment by gardiol** [comment]
This happens to me as well. 502 errors, a lot. Usually after a few page refreshes in a new minutes it works, but it's quite annoying and make it useless for average users.

I understand the technical problem behind, can anything be dome to improve this?

**Comment by meeb** [comment]
There should have been significant improvements with this issue in recent releases. What operations are you performing where a 502 still occurs? How many channels / playlists have you added and how many media items do you have sync'd?

**Comment by gardiol** [comment]
I have 5 channels, of which three are already fully downloaded, two are downloading. I have very big videos (1-4gb) in those. I have 1280 items in queue and over 5000 items already done

**Comment by meeb** [comment]
OK, the size of the videos makes no difference to the performance of tubesync. What operations are you doing where a 502 can occur? Also what platform are you running it on?

**Comment by gardiol** [comment]
Its only downloading those missing videos AFAIK... How can I check what it is doing?

Self hosted on Linux, using docker. On a Core5 with 32gb ram, headless server

**Comment by meeb** [comment]
What are you doing in the web interface that is generating 502 errors, what pages or actions are you doing?

**Comment by gardiol** [comment]
Nothing, just opening up the page the first time, after that, it works

**Comment by gardiol** [comment]
In my logs i see:

```
10.89.0.2 - - [30/Oct/2024:10:54:08 +0100] "GET /tubesync/sources HTTP/1.1" 200 2446 "https://yt.xxx.org/tubesync/" "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"
[2024-10-30 13:01:50 +0100] [326] [CRITICAL] WORKER TIMEOUT (pid:396)
10.89.0.2 - - [30/Oct/2024:13:01:51 +0100] "GET /tubesync/ HTTP/1.1" 502 150 "https://yt.xxx.org/" "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"
2024/10/30 13:01:51 [error] 365#365: *89 upstream prematurely closed connection while reading response header from upstream, client: 10.89.0.2, server: _, request: "GET /tubesync/ HTTP/1.1", upstream: "http://127.0.0.1:8080/tubesync/", host: "yt.xxx.org", referrer: "https://yt.xxx.org/"
[2024-10-30 13:01:51 +0100] [326] [ERROR] Worker (pid:396) was sent SIGKILL! Perhaps out of memory?
```

**Comment by meeb** [comment]
OK, opening the tubesync dashboard basically should always load fine. Your error says the gunicorn worker was killed by the OOM which is why you're getting a 502. Do you have strict resource limits set on your container or something?

**Comment by meeb** [comment]
Yeah when indexing large channels the worker invokes yt-dlp which returns an absolutely massive dictionary of data. This is processed as quickly as possible, but still uses an annoying amount of RAM while it's processing it. Think decoding potentially hundreds of megabytes of JSON big. There's no real way around this at the moment unfortunately.

**Comment by gardiol** [comment]
Ok i see, i will play with podman resources and see if there is anytrhing there and post my findings, it can be useful for others.

**Comment by gardiol** [comment]
This is what "podman stats" says:

```
ID            NAME        CPU %       MEM USAGE / LIMIT  MEM %       NET IO           BLOCK IO           PIDS        CPU TIME       AVG CPU %
1fd2f4285adc  tubesync    30.14%       230.3MB / 33.44GB  0.69%       32.3kB / 16.1kB  8.135GB / 661.5MB  83          39m33.358451s  0.30%
```

this is taked __while__ the page is loading and leading to a 502 error

**Comment by meeb** [comment]
`[2024-10-30 13:01:51 +0100] [326] [ERROR] Worker (pid:396) was sent SIGKILL! Perhaps out of memory?`

Basically, something on your system killed a worker process which is why you got a 502. The most common is the OOM killing it, but there are any number of reasons your system might kill a process. Check your host logs etc.

**Comment by gardiol** [comment]
I will. Consider that it's taking really long anyway, like 20-30 seconds, usually pages show up much faster than that, it might be my NGINX reverse proxy timeout killing it, but after that amount of time, it's well expected

**Comment by meeb** [comment]
I would think it's not actually taking a long time. The behavior of gunicorn is to hang if the worker is forcibly killed, hence the 502 after the nginx proxied request times out. There's no way the nginx timeout can kill anything. Your error is the worker process was forcibly killed by a SIGKILL, a SIGKILL is the same as a `kill -9` so something on your system very much wants the process dead.

**Comment by jonatino** [comment]
I have tubesync setup with 4 sources ~3000 total video files, I can't even load the tubesync ui anymore and it just results in constant 502 errors.

![Image](https://github.com/user-attachments/assets/9dddf33f-7c2b-47f5-9e9f-b596ec2d508f)

**Comment by tcely** [comment]
@jonatino Please open your own new issue. Thank you.
