### ISSUE TITLE
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']

### ISSUE THREAD

**Issue by statik1983** [meeb/tubesync#458]
Installed with Docker Compose pulling latest image.  I think this started after last update.  Keep getting this section of errors:

FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']
[2024-01-13 10:29:44 +0000] [1038] [INFO] Starting gunicorn 21.2.0
[2024-01-13 10:29:44 +0000] [1038] [INFO] Listening at: http://127.0.0.1:8080 (1038)
[2024-01-13 10:29:44 +0000] [1038] [INFO] Using worker: sync
[2024-01-13 10:29:44 +0000] [1038] [ERROR] Unhandled exception in main loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/arbiter.py", line 571, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/arbiter.py", line 642, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/base.py", line 64, in __init__
    self.tmp = WorkerTmp(cfg)
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/workertmp.py", line 23, in __init__
    fd, name = tempfile.mkstemp(prefix="wgunicorn-", dir=fdir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 473, in mkstemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 265, in _sanitize_params
    dir = gettempdir()
          ^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 438, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 431, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 362, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,

**Comment by statik1983** [comment]
I have attempted to recreate the container and pulling image, no luck.

**Comment by meeb** [comment]
I don't think this is anything specifically to do with tubesync. That's a Python error caused by resource exhaustion. Common causes would be the drive the container is stored on is full, the permissions are wrong so /tmp isn't writeable, you've run out of inodes, that sort of thing. Check your server for disk usage and check logs for any errors.

**Comment by meeb** [comment]
I don't think this is a tubesync issue so I'll close this for now.
