### ISSUE TITLE
Please forgive me, I am an idiot:  Error: "Failed to extract_info

### ISSUE THREAD

**Issue by romale23** [meeb/tubesync#476]
Hi, I've been trying to use this off and on for a few months and I am beginning to question my ability to even use a computer. ]

I can't get it to download any channel. I add source put in one and i get this message back
          Error: "Failed to extract_info for "https://www.youtube.com/channel/UCF-uND-dn42ty_EEGBHy_9w/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff."

When i click on the link in the sources, it takes me right to the channel.
I've tried playlist and id.

I'm sorry to bother you with this but i just can't figure out what I'm going wrong and I'm not sure who else to even ask.

**Comment by zxarr** [comment]
+1 for this.  I've just installed fresh...  issue persists for any channel I try.

**Comment by romale23** [comment]
I just put in a palylist with 7 videos, still get same issues. https://www.youtube.com/playlist?list=PLPe5oHlbIf0z5_wzsSn8ySWuNttCH7P-f

**Comment by romale23** [comment]
I'm going to try deleting everything and bringing it in fresh

**Comment by meeb** [comment]
@romale23 First please make sure you're running the latest release from yesterday (v0.13.4). Given the channel you've pasted works fine for me if that still isn't working your error basically means "YouTube returned a 404 when it shouldn't have" which might be something like YouTube has limited or otherwise blocked your IP.

There are some tools to debug this, in a shell type this:

```bash
$ docker exec -ti tubesync python3 /app/manage.py youtube-dl-info "https://www.youtube.com/channel/UCF-uND-dn42ty_EEGBHy_9w/videos"
```

If this is working correctly it should return a huge blob of JSON to the terminal, which is the index of the media on the channel. If something else happens (like a 404) then it's not tubesync or `yt-dlp` but likely an issue with your connection to YouTube itself.

**Comment by romale23** [comment]
I'm guessing this means youtube is somehow blocking mean. 

Showing information for URL: https://www.youtube.com/channel/UCF-uND-dn42ty_EEGBHy_9w/videos
2024-02-27 12:36:24,708 [tubesync/WARNING] [youtube:tab] <urllib3.connection.HTTPSConnection object at 0x7fd83722a290>: Failed to establish a new connection: [Errno 111] Connection refused. Retrying (1/3)...
2024-02-27 12:36:24,709 [tubesync/WARNING] [youtube:tab] <urllib3.connection.HTTPSConnection object at 0x7fd837228650>: Failed to establish a new connection: [Errno 111] Connection refused. Retrying (2/3)...
2024-02-27 12:36:24,710 [tubesync/WARNING] [youtube:tab] <urllib3.connection.HTTPSConnection object at 0x7fd83724c410>: Failed to establish a new connection: [Errno 111] Connection refused. Retrying (3/3)...
2024-02-27 12:36:24,710 [tubesync/WARNING] [youtube:tab] Unable to download webpage: <urllib3.connection.HTTPSConnection object at 0x7fd83724dbd0>: Failed to establish a new connection: [Errno 111] Connection refused (caused by TransportError('<urllib3.connection.HTTPSConnection object at 0x7fd83724dbd0>: Failed to establish a new connection: [Errno 111] Connection refused')). Giving up after 3 retries
2024-02-27 12:36:24,712 [tubesync/WARNING] [youtube:tab] <urllib3.connection.HTTPSConnection object at 0x7fd83724d990>: Failed to establish a new connection: [Errno 111] Connection refused. Retrying (1/3)...
2024-02-27 12:36:24,713 [tubesync/WARNING] [youtube:tab] <urllib3.connection.HTTPSConnection object at 0x7fd83724f210>: Failed to establish a new connection: [Errno 111] Connection refused. Retrying (2/3)...
2024-02-27 12:36:24,714 [tubesync/WARNING] [youtube:tab] <urllib3.connection.HTTPSConnection object at 0x7fd83724dd50>: Failed to establish a new connection: [Errno 111] Connection refused. Retrying (3/3)...
2024-02-27 12:36:24,719 [tubesync/ERROR] ERROR: [youtube:tab] UCF-uND-dn42ty_EEGBHy_9w: Unable to download API page: <urllib3.connection.HTTPSConnection object at 0x7fd837b15790>: Failed to establish a new connection: [Errno 111] Connection refused (caused by TransportError('<urllib3.connection.HTTPSConnection object at 0x7fd837b15790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    main()
  File "/app/manage.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/management/commands/youtube-dl-info.py", line 17, in handle
    info = get_media_info(url)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/sync/youtube.py", line 89, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/channel/UCF-uND-dn42ty_EEGBHy_9w/videos": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.

**Comment by romale23** [comment]
So, feedback: GOT IT!!!!
meeb: Thank you so much for you help. I hate bothering people like yourself because i don't know how all this works well enough. Your last post told me what to look for and i found it :D 
it was the dns server in /etc/resolv.conf
For anyone else looking this up this is what i put in there instead of the 127.whatever.whatever.whatever (i don't remember)
  GNU nano 7.2                                                                 /etc/docker/daemon.json                                                                           {
    "dns": ["10.1.2.3", "8.8.8.8"]
}

**Comment by meeb** [comment]
Heh, absolutely no problem at all. Thanks for posting the solution in case others stumble over this. The default resolver was probably 127.0.0.53. Having this fail could either be an issue with your Docker setup, or with systemd-resolved on the host machine which you might want to investigate further.
