### ISSUE TITLE
Unable to download any videos, all videos being marked skipped. 

### ISSUE THREAD

**Issue by SiR-Marlon** [meeb/tubesync#496]
As the title says, I just got this setup on my unRaid server but it doesn't seem to be working. I added one playlist which has available videos but none of the videos downloaded. They all got skipped. When I manually set them to not skip I get the following error

![image](https://github.com/meeb/tubesync/assets/114263668/67f9810b-3817-43fc-a0c4-cc59cc7d71e8)

![image](https://github.com/meeb/tubesync/assets/114263668/1c55f9de-7bb6-488a-be82-b61dd3ff3ca1)

![image](https://github.com/meeb/tubesync/assets/114263668/d06899cb-a09b-4e18-b73d-3aa667f29bcb)

![image](https://github.com/meeb/tubesync/assets/114263668/a9b929a5-f375-4952-88ee-55e9a6d22659)

I am not sure how to fix this ...

**Comment by SiR-Marlon** [comment]
I am not sure what is going on but I was able to manually download it from the console

![image](https://github.com/meeb/tubesync/assets/114263668/954aa5e6-97c5-49ef-a3df-1494a90c52bf)

But I also noticed that it is saving the video in a completely different format then what I was expecting it is saving the video as WEBM ???

![image](https://github.com/meeb/tubesync/assets/114263668/ae10b040-60a1-46ca-a400-2c0875aac50f)

**Comment by SiR-Marlon** [comment]
Here is the output from the log ...

2024-04-28 17:11:15,298 [tubesync/INFO] Scheduling task to download metadata for: https://www.youtube.com/watch?v=hVucb6wP40w
2024-04-28 17:11:16,573 [tubesync/INFO] Downloading media: hVucb6wP40w (UUID: 78872288-3630-4c71-a917-e5aa2582e4ff) to: "/downloads/video/Season 11 (2024)/2024-04-28_backstage-dodgers-season-11__hVucb6wP40w_.mkv"
Rescheduling Downloading media for "hVucb6wP40w"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 410, in download_media
    format_str, container = media.download_media()
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/models.py", line 1405, in download_media
    raise NoFormatException(f'Cannot download, media "{self.pk}" ({self}) has '
common.errors.NoFormatException: Cannot download, media "78872288-3630-4c71-a917-e5aa2582e4ff" (hVucb6wP40w) has no valid format available
Rescheduling task Downloading media for "hVucb6wP40w" for 0:00:06 later at 2024-04-29 00:11:22.582668+00:00
2024-04-28 17:11:17,751 [tubesync/WARNING] [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "hVucb6wP40w")
2024-04-28 17:11:19,045 [tubesync/WARNING] Media: BackStage Dodgers Season 11 / hVucb6wP40w is older than 10 days, skipping
2024-04-28 17:11:19,068 [tubesync/INFO] Scheduling task to download thumbnail for: Tyler Glasnow’s Journey to MLB - Backstage Dodgers Season 11 (2024) from: https://i.ytimg.com/vi/hVucb6wP40w/maxresdefault.jpg
2024-04-28 17:11:19,078 [tubesync/INFO] Saved 389492 bytes of metadata for: BackStage Dodgers Season 11 / 78872288-3630-4c71-a917-e5aa2582e4ff
2024-04-28 17:11:21,622 [tubesync/WARNING] Download task triggered for media: hVucb6wP40w (UUID: 78872288-3630-4c71-a917-e5aa2582e4ff) but it is now marked to be skipped, not downloading thumbnail
2024-04-28 17:11:26,736 [tubesync/WARNING] Download task triggered for  media: hVucb6wP40w (UUID: 78872288-3630-4c71-a917-e5aa2582e4ff) but it is now marked to be skipped, not downloading

**Comment by tcely** [comment]
```
2024-04-28 17:11:19,045 [tubesync/WARNING] Media: BackStage Dodgers Season 11 / hVucb6wP40w is older than 10 days, skipping
```

The source is configured to not download videos older than 10 days.
