### ISSUE TITLE
cannot write mode RGBA as JPEG - Thumbnail downloading

### ISSUE THREAD

**Issue by timwhite** [meeb/tubesync#504]
Got this traceback recently for a channel called Hand Tool Rescue (`@HandToolRescue`). Not sure what they have done to break the image, but it's probably something we want to handle.

```
Rescheduling Check download directory exists for source "Hand Tool Rescue"

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/dist-packages/PIL/JpegImagePlugin.py", line 650, in _save

    rawmode = RAWMODE[im.mode]

              ~~~~~~~^^^^^^^^^

KeyError: 'RGBA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner

    func(*args, **kwargs)

  File "/app/sync/tasks.py", line 259, in download_source_images

    i.save(image_file, 'JPEG', quality=85, optimize=True, progressive=True)

  File "/usr/local/lib/python3.11/dist-packages/PIL/Image.py", line 2459, in save

    save_handler(self, fp, filename)

  File "/usr/local/lib/python3.11/dist-packages/PIL/JpegImagePlugin.py", line 653, in _save

    raise OSError(msg) from e

OSError: cannot write mode RGBA as JPEG

Rescheduling task Check download directory exists for source "Hand Tool Rescue" for 0:00:06 later at 2024-06-02 08:53:49.355880+00:00
```

**Comment by meeb** [comment]
Odd, I guess that's the upstream thumbnail now being transparent or supporting transparency and that attempting to be passed through to JPEG, which of course doesn't have an alpha channel. I'll stuff in a `i.convert('RGB')` somewhere to make sure it's forced into RGB so it can be saved as a JPEG.
