### ISSUE TITLE
Task fails because of partially downloaded file

### ISSUE THREAD

**Issue by wsdookadr** [meeb/tubesync#529]
One of the playlists I've added in Tubesync has a video which won't download and the task for it always fails.

Here's a relevant fragment of docker logs for this:

<details>
<summary>docker logs</summary>

```
tubesync  | 2024-08-08 22:25:29,808 [tubesync/INFO] Downloading media: r33XEcPJIKw (UUID: f698e2ac-4a7e-4f3e-b215-6b6de5e6b9d4) to: "/downloads/video/Organizational-Ethics-Daniel-Bonevac/2021-06-25_organizational-ethics_relational-models-theory_r33XEcPJIKw_1080p-avc1-mp4a.mkv"
tubesync  | ERROR: unable to download video data: HTTP Error 416: Requested range not satisfiable
tubesync  | 2024-08-08 22:25:32,946 [tubesync/ERROR] Failed to download media: r33XEcPJIKw (UUID: f698e2ac-4a7e-4f3e-b215-6b6de5e6b9d4) to disk, expected outfile does not exist: /downloads/video/Organizational-Ethics-Daniel-Bonevac/2021-06-25_organizational-ethics_relational-models-theory_r33XEcPJIKw_1080p-avc1-mp4a.mkv
tubesync  | Rescheduling Downloading media for "Relational Models Theory"
tubesync  | Traceback (most recent call last):
tubesync  |   File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
tubesync  |     func(*args, **kwargs)
tubesync  |   File "/app/sync/tasks.py", line 452, in download_media
tubesync  |     raise DownloadFailedException(err)
tubesync  | common.errors.DownloadFailedException: Failed to download media: r33XEcPJIKw (UUID: f698e2ac-4a7e-4f3e-b215-6b6de5e6b9d4) to disk, expected outfile does not exist: /downloads/video/Organizational-Ethics-Daniel-Bonevac/2021-06-25_organizational-ethics_relational-models-theory_r33XEcPJIKw_1080p-avc1-mp4a.mkv
tubesync  | Rescheduling task Downloading media for "Relational Models Theory" for 0:10:30 later at 2024-08-08 19:36:02.963228+00:00
```

</details>

Note the HTTP 416 error above related to this issue yt-dlp/yt-dlp#8313 .

I tried deleting this video from the sync_media table in the db and deleting the .part file from disk but that didn't fix the problem(it's still not downloading). Yes I've also reset the tasks and have restarted the docker container too.

Is there a workaround for this?
Thanks!

**Comment by wsdookadr** [comment]
Okay my bad, it seems after resetting and restarting again, it managed to pull the video.
