### ISSUE TITLE
Thumbnail is not embedded into audio files even with "Embed Thumbnails" turned on

### ISSUE THREAD

**Issue by SSS-Says-Snek** [meeb/tubesync#538]
I'm using tubesync to download audio files from my playlist and play them on my phone (with the Musicolet app). I turned on both "Embed thumbnail" and "Embed metadata", and while metadata seems to be working fine, the thumbnails are not appearing in the previews. 
![image](https://github.com/user-attachments/assets/d28a9f1b-74d5-44b2-af2b-90503f06913f)

# What I tried
I tried many different combinations of embedding thumbnail, embedding metadata, writing NFO, and changing the audio codec. None of them had any embedded thumbnails.

I also wrote a test script to see if anything was wrong with yt-dlp. However, I saw that this actually did embed the thumbnail into the file:
```py
import yt_dlp

ytopts = {
    'format': 'm4a',
    'writethumbnail': True,
    'postprocessors': [{'key': 'FFmpegMetadata', 'add_metadata': True}, {'key': 'EmbedThumbnail'}],
    'quiet': False
}
with yt_dlp.YoutubeDL(ytopts) as y:
    y.download(['https://www.youtube.com/watch?v=aSXtXLAVgkE'])
```
with the output
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=aSXtXLAVgkE
[youtube] aSXtXLAVgkE: Downloading webpage
[youtube] aSXtXLAVgkE: Downloading ios player API JSON
[youtube] aSXtXLAVgkE: Downloading web creator player API JSON
[youtube] aSXtXLAVgkE: Downloading m3u8 information
[info] aSXtXLAVgkE: Downloading 1 format(s): 140
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: Rachmaninoff： Piano Concerto #3 (Weissenberg 1968) [with score] [aSXtXLAVgkE].webp
[download] Destination: Rachmaninoff： Piano Concerto #3 (Weissenberg 1968) [with score] [aSXtXLAVgkE].m4a
[download] 100% of   40.05MiB in 00:00:04 at 9.37MiB/s
[FixupM4a] Correcting container of "Rachmaninoff： Piano Concerto #3 (Weissenberg 1968) [with score] [aSXtXLAVgkE].m4a"
[Metadata] Adding metadata to "Rachmaninoff： Piano Concerto #3 (Weissenberg 1968) [with score] [aSXtXLAVgkE].m4a"
[ThumbnailsConvertor] Converting thumbnail "Rachmaninoff： Piano Concerto #3 (Weissenberg 1968) [with score] [aSXtXLAVgkE].webp" to png
[EmbedThumbnail] mutagen: Adding thumbnail to "Rachmaninoff： Piano Concerto #3 (Weissenberg 1968) [with score] [aSXtXLAVgkE].m4a"
```
Tubesync            | Test script
:-------------------------:|:-------------------------:
![image](https://github.com/user-attachments/assets/b63e0b85-6763-4e15-8912-492f165e9ae5)  |  ![image](https://github.com/user-attachments/assets/fe0ebd54-4857-4d3b-a576-6abdb9fa36a4)

I skimmed tubesync's codebase, and I think that my test script's `writethumbnail` option may have something to do with it? I'm not sure though, since I can't test it because manually running tubesync without a container doesn't seem to be working for me (#534)

I also might be entirely getting the wrong idea of what embedding thumbnails is supposed to do 😅 Regardless, loving tubesync rn! Keep up the good work!

**Comment by DorH92** [comment]
Same here. Thumbnail doesn't get embedded to audio files..

**Comment by DorH92** [comment]
@meeb 

Unlike him, I didn't configure thumbnails to be downloaded separately but only to be embedded in the audio file. And in my case it still doesn't get embedded.

**Comment by mjessa12** [comment]
did you get this to work?  For my with audio only files it is not embedding the thumbnail.  Navidrome is showing default pictures for all songs i have downloaded

**Comment by tcely** [comment]
Is this still an issue?

The post processing options for `yt-dlp` were reworked recently.

**Comment by An7hrax** [comment]
```
2025-02-28 13:41:41,177 [tubesync/INFO] [EmbedThumbnail] started for: xY2Z7GvWBk8: Dankey Kong - JAG SKITER I feat. Östblockarn & ERK (DIY VIDEO)
[ThumbnailsConvertor] Converting thumbnail "/downloads/cache/.yt_dlp-xY2Z7GvWBk8-_poqayav/Dankey Kong - JAG SKITER I feat. Östblockarn & ERK (DIY VIDEO)_xY2Z7GvWBk8_opus.ogg.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:/downloads/cache/.yt_dlp-xY2Z7GvWBk8-_poqayav/Dankey Kong - JAG SKITER I feat. Östblockarn & ERK (DIY VIDEO)_xY2Z7GvWBk8_opus.ogg.webp' -update 1 -movflags +faststart 'file:/downloads/cache/.yt_dlp-xY2Z7GvWBk8-_poqayav/Dankey Kong - JAG SKITER I feat. Östblockarn & ERK (DIY VIDEO)_xY2Z7GvWBk8_opus.ogg.png'
ERROR: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/m4v/mov
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/yt_dlp/YoutubeDL.py", line 3714, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yt_dlp/postprocessor/common.py", line 127, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/yt_dlp/postprocessor/embedthumbnail.py", line 222, in run
    raise EmbedThumbnailPPError('Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/m4v/mov')
yt_dlp.postprocessor.embedthumbnail.EmbedThumbnailPPError: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/m4v/mov
```

Think so.
Running these versions in docker:
[TubeSync](https://github.com/meeb/tubesync) version 0.13.7 with[ yt-dlp](https://github.com/yt-dlp/yt-dlp) version 2025.02.19 and[ FFmpeg](https://ffmpeg.org/) version N-118500-g08e37fa082-20250218.

Config for the source:
Source Resolution: Audio Only
Source Video Codec: VP9
Source Audio Codec: OPUS
Copy Thumbnails: False (since this only saves a image in the folder)
Embed Metadata: True
Embed Thumbnail: True
Sponsorblock: False

**Comment by SSS-Says-Snek** [comment]
I think m4a's working as well, I'm getting the youtube thumbnails for the most recent things I've added to my playlist. Thanks for all the hard work!
