### ISSUE TITLE
This video is no longer available due to a copyright claim by

### ISSUE THREAD

**Issue by ghost** [meeb/tubesync#542]
Suggesto to remove or mark video not avail in the list.

```bash
2024-09-13 11:46:21,718 [tubesync/INFO] Writing media NFO file to: to: /downloads/video/Sci-Fi Era/2024-07-08_sci-fi-era_ranking-the-21-books-i-just-read-sci-fi-fantasy-and-lit-fic_ojTV8wQ6BxI_1080p-vp09-opus.nfo
2024-09-13 11:46:26,990 [tubesync/ERROR] ERROR: [youtube] hyCCWHhH6R4: Video unavailable. This video is no longer available due to a copyright claim by Synergetic Distribution
Rescheduling Downloading metadata for "a72ce0ff-4c0d-4fb7-bf48-7c2e55a9299b"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 291, in download_media_metadata
    metadata = media.index_metadata()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sync/models.py", line 1494, in index_metadata
    return indexer(self.url)
           ^^^^^^^^^^^^^^^^^
  File "/app/sync/youtube.py", line 89, in get_media_info
    raise YouTubeError(f'Failed to extract_info for "{url}": No metadata was '
sync.youtube.YouTubeError: Failed to extract_info for "https://www.youtube.com/watch?v=hyCCWHhH6R4": No metadata was returned by youtube-dl, check for error messages in the logs above. This task will be retried later with an exponential backoff.
Rescheduling task Downloading metadata for "a72ce0ff-4c0d-4fb7-bf48-7c2e55a9299b" for 0:04:21 later at 2024-09-13 14:50:48.003562+00:00
```

**Comment by meeb** [comment]
Media items will be retried for about a day and then mark themselves as a failed download already.
