### ISSUE TITLE
_youtubedl_tempdir_path dir not set, yet attempting to access it

### ISSUE THREAD

**Issue by aksiksi** [meeb/tubesync#582]
Hello! Thanks for the awesome app!

Recently, my Tubesync container has been crashing on init at this line: https://github.com/meeb/tubesync/blob/679f77b6b45f2b4a3ec6e6d25259022dd00afbd1/tubesync/sync/youtube.py#L25

Since I have not set the `YOUTUBE_DL_TEMPDIR` env variable anywhere, it's unclear why Tubesync is even hitting this code.

Here is my Compose file. One thing to note is that the root `/downloads` directory is **not** mapped - only the `audio` and `video` subdirectories are valid. This is why the `.ignore` file check fails.

```yaml
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    environment:
      TZ: ${TIMEZONE}
      PUID: ${PUID}
      PGID: ${PGID}
      # https://github.com/meeb/tubesync/blob/main/docs/other-database-backends.md
      DATABASE_CONNECTION: postgresql://postgres:postgres@tubesync-db:5432/tubesync
      # https://github.com/meeb/tubesync#advanced-configuration
      DJANGO_URL_PREFIX: /tubesync/
      TUBESYNC_RESET_DOWNLOAD_DIR: "False"
    volumes:
      - /var/volumes/tubesync:/config
      - /mnt/media/Kids/YouTube:/downloads/video/Kids
      - /mnt/media/YouTube/Video:/downloads/video/YouTube
      - /mnt/media/YouTube/Audio:/downloads/audio/YouTube
    depends_on:
      - tubesync-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tubesync.rule=Host(`home.internal.${DOMAIN}`) && PathPrefix(`/tubesync`)"
      - "traefik.http.routers.tubesync.tls.certresolver=htpc"
      - "io.containers.autoupdate=registry"
    logging:
      driver: "journald"
    restart: unless-stopped
```

Here is the full traceback:

```
Dec 14 16:50:00 djerba tubesync[1386537]: s6-rc: info: service s6rc-oneshot-runner: starting
Dec 14 16:50:00 djerba tubesync[1386537]: s6-rc: info: service s6rc-oneshot-runner successfully started
Dec 14 16:50:00 djerba tubesync[1386537]: s6-rc: info: service fix-attrs: starting
Dec 14 16:50:00 djerba tubesync[1386537]: s6-rc: info: service tubesync-init: starting
Dec 14 16:50:00 djerba tubesync[1386537]: s6-rc: info: service fix-attrs successfully started
Dec 14 16:50:00 djerba tubesync[1386537]: s6-rc: info: service legacy-cont-init: starting
Dec 14 16:50:00 djerba tubesync[1386537]: s6-rc: info: service legacy-cont-init successfully started
Dec 14 16:50:01 djerba tubesync[1386537]: 2024-12-14 16:50:01,211 [tubesync/INFO] Using database connection: django.db.backends.postgresql://postgres:[hidden]@tubesync-db:5432/tu>
Dec 14 16:50:01 djerba tubesync[1386537]: Traceback (most recent call last):
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/app/manage.py", line 18, in <module>
Dec 14 16:50:01 djerba tubesync[1386537]:     main()
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/app/manage.py", line 14, in main
Dec 14 16:50:01 djerba tubesync[1386537]:     execute_from_command_line(sys.argv)
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
Dec 14 16:50:01 djerba tubesync[1386537]:     utility.execute()
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 395, in execute
Dec 14 16:50:01 djerba tubesync[1386537]:     django.setup()
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/usr/local/lib/python3.11/dist-packages/django/__init__.py", line 24, in setup
Dec 14 16:50:01 djerba tubesync[1386537]:     apps.populate(settings.INSTALLED_APPS)
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/usr/local/lib/python3.11/dist-packages/django/apps/registry.py", line 114, in populate
Dec 14 16:50:01 djerba tubesync[1386537]:     app_config.import_models()
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/usr/local/lib/python3.11/dist-packages/django/apps/config.py", line 301, in import_models
Dec 14 16:50:01 djerba tubesync[1386537]:     self.models_module = import_module(models_module_name)
Dec 14 16:50:01 djerba tubesync[1386537]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
Dec 14 16:50:01 djerba tubesync[1386537]:     return _bootstrap._gcd_import(name[level:], package, level)
Dec 14 16:50:01 djerba tubesync[1386537]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 14 16:50:01 djerba tubesync[1386537]:   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
Dec 14 16:50:01 djerba tubesync[1386537]:   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
Dec 14 16:50:01 djerba tubesync[1386537]:   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
Dec 14 16:50:01 djerba tubesync[1386537]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Dec 14 16:50:01 djerba tubesync[1386537]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Dec 14 16:50:01 djerba tubesync[1386537]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/app/sync/models.py", line 19, in <module>
Dec 14 16:50:01 djerba tubesync[1386537]:     from .youtube import (get_media_info as get_youtube_media_info,
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/app/sync/youtube.py", line 25, in <module>
Dec 14 16:50:01 djerba tubesync[1386537]:     (_youtubedl_tempdir_path / '.ignore').touch(exist_ok=True)
Dec 14 16:50:01 djerba tubesync[1386537]:   File "/usr/lib/python3.11/pathlib.py", line 1109, in touch
Dec 14 16:50:01 djerba tubesync[1386537]:     fd = os.open(self, flags, mode)
Dec 14 16:50:01 djerba tubesync[1386537]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 14 16:50:01 djerba tubesync[1386537]: PermissionError: [Errno 13] Permission denied: '/downloads/cache/.ignore'
Dec 14 16:50:01 djerba tubesync[1386537]: s6-rc: warning: unable to start service tubesync-init: command exited 1
```

Thanks!

**Comment by aksiksi** [comment]
OK, seems like this was added in https://github.com/meeb/tubesync/pull/556.

In particular, the path is set to a default here - `/downloads/cache`: https://github.com/meeb/tubesync/blob/679f77b6b45f2b4a3ec6e6d25259022dd00afbd1/tubesync/tubesync/local_settings.py.container#L64

To fix this, I've mapped in that exact path like so:

```diff
diff --git a/hosts/djerba/compose.yml b/hosts/djerba/compose.yml
index a1122ab..01bf7cc 100644
--- a/hosts/djerba/compose.yml
+++ b/hosts/djerba/compose.yml
@@ -325,6 +325,7 @@ services:
       TUBESYNC_RESET_DOWNLOAD_DIR: "False"
     volumes:
       - /var/volumes/tubesync:/config
+      - /mnt/media/Downloads/tubesync/cache:/downloads/cache
       - /mnt/media/Kids/YouTube:/downloads/video/Kids
       - /mnt/media/YouTube/Video:/downloads/video/YouTube
       - /mnt/media/YouTube/Audio:/downloads/audio/YouTube
```
