### ISSUE TITLE
NFO file not created

### ISSUE THREAD

**Issue by henrikmaurin** [meeb/tubesync#609]
Since about a week, NFO files are no longer created for my downloaded videos.
I have this option ticked for all my channels.

I can see the info embedded in the mkv-file, so there is not a problem with getting the description
For the videos I also save an image for, the image is still created.

EDIT
I also tried ticking the export json file, which works. So it seems to be only the export NFO that has been broken

**Comment by henrikmaurin** [comment]
LOGS:
```
TubeSync  | [MoveFiles] Moving file "/downloads/cache/Linus Tech Tips.(2024-12-26) - I Built The Ultimate Hidden Gaming Room.mkv" to "/downloads/video/TubeSync/Linus Tech Tips/Linus Tech Tips.(2024-12-26) - I Built The Ultimate Hidden Gaming Room.mkv"
TubeSync  | 2024-12-28 13:07:57,191 [tubesync/INFO] Successfully downloaded media: tLhfuc_KCpM (UUID: df313ac9-0ed9-4c2e-b06c-360c47c149e9) to: "/downloads/video/TubeSync/Linus Tech Tips/Linus Tech Tips.(2024-12-26) - I Built The Ultimate Hidden Gaming Room.mkv"
TubeSync  | 2024-12-28 13:07:57,308 [tubesync/INFO] Copying media thumbnail from: /config/media/thumbs/df/df313ac9-0ed9-4c2e-b06c-360c47c149e9.jpg to: /downloads/video/TubeSync/Linus Tech Tips/Linus Tech Tips.(2024-12-26) - I Built The Ultimate Hidden Gaming Room.jpg
TubeSync  | 2024-12-28 13:07:57,348 [tubesync/INFO] Writing media NFO file to: /downloads/video/TubeSync/Linus Tech Tips/Linus Tech Tips.(2024-12-26) - I Built The Ultimate Hidden Gaming Room.nfo
TubeSync  | Rescheduling Downloading media for "I Built The Ultimate Hidden Gaming Room"
TubeSync  | Traceback (most recent call last):
TubeSync  |   File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
TubeSync  |     func(*args, **kwargs)
TubeSync  |   File "/app/sync/tasks.py", line 449, in download_media
TubeSync  |     write_text_file(media.nfopath, media.nfoxml)
TubeSync  |   File "/app/sync/utils.py", line 129, in write_text_file
TubeSync  |     raise ValueError(f'File cannot be edited or removed: {filepath}')
TubeSync  | ValueError: File cannot be edited or removed: /downloads/video/TubeSync/Linus Tech Tips/Linus Tech Tips.(2024-12-26) - I Built The Ultimate Hidden Gaming Room.nfo
TubeSync  | Rescheduling task Downloading media for "I Built The Ultimate Hidden Gaming Room" for 0:00:06 later at 2024-12-28 12:08:17.661309+00:00
TubeSync  | 2024-12-28 13:08:22,024 [tubesync/WARNING] Download task triggered for media: tLhfuc_KCpM (UUID: df313ac9-0ed9-4c2e-b06c-360c47c149e9) but it has already been marked as downloaded, not downloading again
```

So I can see 2 separate problems here (I think)
1. When trying to write the NFO, the code checking for permissions prevents the NFO to be written. (On my first try, the downloded mkv was still in the destination folder causing a similar error, but at the step where the video file should be downloaded)

2. The rescheduling gets cancelled by it already being marked downloaded.

If the problem is caused by folder permissions on my host, could someone advice how to set them properly. But since the the other files getting created, I really cant see that beeing the problem

**Comment by henrikmaurin** [comment]
Could the problem be that I organize my downloads in subfolders?
Like this:
Directory:  TubeSync/Linus Tech Tips

**Comment by henrikmaurin** [comment]
Ok, so I managed to add some logging myself
Seems the nfo filepath in is_editable is expanded to my host filesystem path

Since I don't know Python, I'm not going to try fix this.

```
def file_is_editable(filepath):
    '''
        Checks that a file exists and the file is in an allowed predefined tuple of
        directories we want to allow writing or deleting in.
    '''
    allowed_paths = (
        # Media item thumbnails
        Path(str(settings.MEDIA_ROOT)).resolve(),

        # Downloaded media files
        Path(str(settings.DOWNLOAD_ROOT)).resolve(),
    )
    log.info(allowed_paths)    
    filepath = Path(str(filepath)).resolve()
    if not filepath.is_file():
        log.info(f'is_file failed: {filepath}')
        return False
    log.info(f'filepath: {filepath}')
    for allowed_path in allowed_paths:
        log.info(f'allowed_path: {allowed_path}')
        log.info(f'commonpath: {os.path.commonpath([allowed_path, filepath])}')
        if str(allowed_path) == os.path.commonpath([allowed_path, filepath]):
            return True
    return False
```

First row from download_media, where the filename is a path within the container
```
TubeSync  | 2024-12-28 15:56:40,001 [tubesync/INFO] Writing media NFO file to: /downloads/video/TubeSync/Linus Tech Tips/Linus Tech Tips.(2024-12-26) - I Built The Ultimate Hidden Gaming Room [tLhfuc_KCpM] [tvdb336426].nfo

TubeSync  | 2024-12-28 15:58:18,297 [tubesync/INFO] (PosixPath('/config/media'), PosixPath('/downloads'))
TubeSync  | 2024-12-28 15:58:18,297 [tubesync/INFO] filepath: /Downloaded/Video/TubeSync/Linus Tech Tips/15o7vlc3.tmp
TubeSync  | 2024-12-28 15:58:18,297 [tubesync/INFO] allowed_path: /config/media
TubeSync  | 2024-12-28 15:58:18,297 [tubesync/INFO] commonpath: /
TubeSync  | 2024-12-28 15:58:18,297 [tubesync/INFO] allowed_path: /downloads
TubeSync  | 2024-12-28 15:58:18,297 [tubesync/INFO] commonpath: /
```

**Comment by meeb** [comment]
This looks like a path or volume issue. What's `/Downloaded/` ? That's outside of `/downloads/` and not part of the "permitted" directories that can be written to.

**Comment by henrikmaurin** [comment]
Yes, `/Downloaded/` is a local symlink on the host
When download_media logs the path for the NFO file, it seems to be a path inside the container

but in write_text_file the TubeSynk part gets replaces by the symlink for TubeSync on my host
My guess is the `NamedTemporaryFile` part does something.

I'm happy to add more logs if it would help.


Relevant parts of my docker compose file

```
volumes:
      - /Downloaded:/Downloaded
      - /srv/data/TubeSync:/downloads    
      - /Downloading/tubesync/cache:/downloads/cache

```

Relevant Symlinks on my server
TubeSync -> /Downloaded/Video/Tv
Downloaded -> /srv/data/Downloaded
Downloading -> /srv/data/Downloading
data -> /srv/dev-disk-by-uuid-18c2608f-c77d-4296-bbeb-d354839fac68

**Comment by meeb** [comment]
Do you have some custom container config? What does your setup use `/Downloaded/` for? Your log snippet was for two different files so it's not especially useful to debug this unfortunately. Obviously any calls to `file_is_editable(...)` with a path to a file in `/Downloaded/...` will return False as it's not within `/downloads/` or `/config/media/`.

**Comment by henrikmaurin** [comment]
No, I don't think I have something custom, except for using symlinks containing another symlink on my host
I have to mount `/Downloaded`, because TubeSync in `/srv/data/TubeSync` is using the symlink `/Downloaded`

I added som more logging, but it doesn't really add anything relevant. Did a new run for a different file


`Path(str(filepath)).resolve() ` seems to resolve the path to the path of the file on the host.
The way I am debugging is by editing a copy of utils.py and mounting it in the container. Is there an easier way for me to debug this?

```
def file_is_editable(filepath):
    '''
        Checks that a file exists and the file is in an allowed predefined tuple of
        directories we want to allow writing or deleting in.
    '''
    allowed_paths = (
        # Media item thumbnails
        Path(str(settings.MEDIA_ROOT)).resolve(),

        # Downloaded media files
        Path(str(settings.DOWNLOAD_ROOT)).resolve(),
    )
    log.info(f'1(file_is_editable) filepath (before resolve): {filepath}')
    log.info(f'2(file_is_editable) {allowed_paths}')
    filepath = Path(str(filepath)).resolve()
    if not filepath.is_file():
        log.info(f'is_file failed: {filepath}')
        return False
    log.info(f'3(file_is_editable) filepath (after resolve): {filepath}')
    for allowed_path in allowed_paths:
        log.info(f'allowed_path: {allowed_path}')
        log.info(f'commonpath: {os.path.commonpath([allowed_path, filepath])}')
        if str(allowed_path) == os.path.commonpath([allowed_path, filepath]):
            return True
    return False


def write_text_file(filepath, filedata):
    if not isinstance(filedata, str):
        raise TypeError(f'filedata must be a str, got "{type(filedata)}"')
    filepath_dir = str(Path(filepath).parent)
    log.info(f'1(write_text_file) filepath: {filepath}')
    log.info(f'2(write_text_file) filepath_dir: {filepath_dir}')
    with NamedTemporaryFile(mode='wt', suffix='.tmp', prefix='', dir=filepath_dir, delete=False) as f:
        new_filepath = Path(f.name)
        bytes_written = f.write(filedata)
    log.info(f'3(write_text_file) new_filepath: {new_filepath}')
    # chmod a+r temp_file
    old_mode = new_filepath.stat().st_mode
    new_filepath.chmod(0o444 | old_mode)
    if not file_is_editable(new_filepath):
        new_filepath.unlink()
        raise ValueError(f'File cannot be edited or removed: {filepath}')
    new_filepath.replace(filepath)
    return bytes_written
```
```
TubeSync  | [MoveFiles] Moving file "/downloads/cache/ShortCircuit.(2024-12-29) - I Can’t Believe Apple Sells These… - Weird Apple Store Products.mkv" to "/downloads/video/TubeSync/ShortCircuit/ShortCircuit.(2024-12-29) - I Can’t Believe Apple Sells These… - Weird Apple Store Products.mkv"
TubeSync  | 2024-12-30 18:53:36,315 [tubesync/INFO] Successfully downloaded media: n4WDRyrzVmw (UUID: 30c1dfb5-494d-45bf-a051-f1c4b13b4503) to: "/downloads/video/TubeSync/ShortCircuit/ShortCircuit.(2024-12-29) - I Can’t Believe Apple Sells These… - Weird Apple Store Products.mkv"
TubeSync  | 2024-12-30 18:53:38,191 [tubesync/INFO] Copying media thumbnail from: /config/media/thumbs/30/30c1dfb5-494d-45bf-a051-f1c4b13b4503.jpg to: /downloads/video/TubeSync/ShortCircuit/ShortCircuit.(2024-12-29) - I Can’t Believe Apple Sells These… - Weird Apple Store Products.jpg
TubeSync  | 2024-12-30 18:53:38,228 [tubesync/INFO] Writing media NFO file to: /downloads/video/TubeSync/ShortCircuit/ShortCircuit.(2024-12-29) - I Can’t Believe Apple Sells These… - Weird Apple Store Products.nfo
TubeSync  | 2024-12-30 18:54:59,482 [tubesync/INFO] 1(write_text_file) filepath: /downloads/video/TubeSync/ShortCircuit/ShortCircuit.(2024-12-29) - I Can’t Believe Apple Sells These… - Weird Apple Store Products.nfo
TubeSync  | 2024-12-30 18:54:59,482 [tubesync/INFO] 2(write_text_file) filepath_dir: /downloads/video/TubeSync/ShortCircuit
TubeSync  | 2024-12-30 18:54:59,482 [tubesync/INFO] 3(write_text_file) new_filepath: /downloads/video/TubeSync/ShortCircuit/b_bqp8x1.tmp
TubeSync  | 2024-12-30 18:54:59,483 [tubesync/INFO] 1(file_is_editable) filepath (before resolve): /downloads/video/TubeSync/ShortCircuit/b_bqp8x1.tmp
TubeSync  | 2024-12-30 18:54:59,483 [tubesync/INFO] 2(file_is_editable) (PosixPath('/config/media'), PosixPath('/downloads'))
TubeSync  | 2024-12-30 18:54:59,483 [tubesync/INFO] 3(file_is_editable) filepath (after resolve): /Downloaded/Video/Tv/ShortCircuit/b_bqp8x1.tmp
TubeSync  | 2024-12-30 18:54:59,483 [tubesync/INFO] allowed_path: /config/media
TubeSync  | 2024-12-30 18:54:59,483 [tubesync/INFO] commonpath: /
TubeSync  | 2024-12-30 18:54:59,483 [tubesync/INFO] allowed_path: /downloads
TubeSync  | 2024-12-30 18:54:59,483 [tubesync/INFO] commonpath: /
TubeSync  | Rescheduling Downloading media for "I Can’t Believe Apple Sells These… - Weird Apple Store Products"
TubeSync  | Traceback (most recent call last):
TubeSync  |   File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
TubeSync  |     func(*args, **kwargs)
TubeSync  |   File "/app/sync/tasks.py", line 449, in download_media
TubeSync  |     write_text_file(media.nfopath, media.nfoxml)
TubeSync  |   File "/app/sync/utils.py", line 139, in write_text_file
TubeSync  |     raise ValueError(f'File cannot be edited or removed: {filepath}')
TubeSync  | ValueError: File cannot be edited or removed: /downloads/video/TubeSync/ShortCircuit/ShortCircuit.(2024-12-29) - I Can’t Believe Apple Sells These… - Weird Apple Store Products.nfo
TubeSync  | Rescheduling task Downloading media for "I Can’t Believe Apple Sells These… - Weird Apple Store Products" for 0:00:06 later at 2024-12-30 17:55:06.072773+00:00
TubeSync  | 2024-12-30 18:55:12,465 [tubesync/WARNING] Download task triggered for media: n4WDRyrzVmw (UUID: 30c1dfb5-494d-45bf-a051-f1c4b13b4503) but it has already been marked as downloaded, not downloading again

```

**Comment by henrikmaurin** [comment]
I removed the call to file_is_editable on my local setup
```
#if not file_is_editable(new_filepath):
#        new_filepath.unlink()
#        raise ValueError(f'File cannot be edited or removed: {filepath}')
```
Now a NFO is created alongside the other files again. While this isn't a real sollution, it works for me until a real sollution can be found.

**Comment by henrikmaurin** [comment]
I did some more testing.

Changing .resolve() to .absolute() in file_is_editable fixes my problem.
Now my symlinked paths resolves to the correct paths

I've read that absolute() is undocumented, but is still recommended by a lot of people. For me, changing to absolute would be preferred, but I don't know if it will break things for others. So if I could have en option to use absolute instead of resolve in that case, I would be happy

**Comment by ZeblodS** [comment]
I have a similar issue since around the 29th of December, which seem to coincide when [henrikmaurin](https://github.com/henrikmaurin) started to have this issue. I don't remember but I probably updated the TubeSync docker app that day.

New videos are created in the database (and TubeSync webUI), the video itself and the thumbnail is correctly downloaded, but the NFO file is not created.

A temporary file (for example 9i7p5lpo.tmp or djdyt0_7.tmp, always 8 characters followed by .tmp) is created, which contains the data of the NFO file, alongside the video and thumbnail files. But it isn't named correctly. Here is the displayed log:

```
tubesync  | 2025-01-06 13:43:43,515 [tubesync/INFO] Downloading media: 6sAv1Dhmt20 (UUID: 75963aba-81cd-4ea7-9aae-1ecacbb6f333) to: "/downloads/video/Millomaker/2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.mkv"
tubesync  | 2025-01-06 13:43:58,384 [tubesync/INFO] [youtube-dl] finished downloading: 2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.f614.mp4 - 224.16MiB in 00:00:12
tubesync  | 2025-01-06 13:43:59,023 [tubesync/INFO] [youtube-dl] downloading: 2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.f251.webm - 49.7% of 23.90MiB at 33.13MiB/s, 00:00 remaining
tubesync  | 2025-01-06 13:43:59,170 [tubesync/INFO] [youtube-dl] downloading: 2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.f251.webm - 74.8% of 23.90MiB at 38.54MiB/s, 00:00 remaining
tubesync  | 2025-01-06 13:43:59,288 [tubesync/INFO] [youtube-dl] downloading: 2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.f251.webm - 84.8% of 23.90MiB at 16.62MiB/s, 00:00 remaining
tubesync  | 2025-01-06 13:43:59,363 [tubesync/INFO] [youtube-dl] downloading: 2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.f251.webm - 100.0% of 23.90MiB at 39.04MiB/s, 00:00 remaining
tubesync  | 2025-01-06 13:43:59,364 [tubesync/INFO] [youtube-dl] finished downloading: 2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.f251.webm - 23.90MiB in 00:00:00
tubesync  | ERROR: [Errno 1] Operation not permitted: '/downloads/video/Millomaker/2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.mkv'
tubesync  | 2025-01-06 13:44:00,787 [tubesync/INFO] Successfully downloaded media: 6sAv1Dhmt20 (UUID: 75963aba-81cd-4ea7-9aae-1ecacbb6f333) to: "/downloads/video/Millomaker/2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.mkv"
tubesync  | 2025-01-06 13:44:00,814 [tubesync/INFO] Copying media thumbnail from: /config/media/thumbs/75/75963aba-81cd-4ea7-9aae-1ecacbb6f333.jpg to: /downloads/video/Millomaker/2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.jpg
tubesync  | 2025-01-06 13:44:00,826 [tubesync/INFO] Writing media NFO file to: /downloads/video/Millomaker/2025-01-05_millomaker_reparation-apple-vs-samsung_-vp9-opus.nfo
tubesync  | Rescheduling Downloading media for "Réparation : Apple VS Samsung"
tubesync  | Traceback (most recent call last):
tubesync  |   File "/usr/local/lib/python3.11/dist-packages/background_task/tasks.py", line 43, in bg_runner
tubesync  |     func(*args, **kwargs)
tubesync  |   File "/app/sync/tasks.py", line 449, in download_media
tubesync  |     write_text_file(media.nfopath, media.nfoxml)
tubesync  |   File "/app/sync/utils.py", line 126, in write_text_file
tubesync  |     new_filepath.chmod(0o444 | old_mode)
tubesync  |   File "/usr/lib/python3.11/pathlib.py", line 1133, in chmod
tubesync  |     os.chmod(self, mode, follow_symlinks=follow_symlinks)
tubesync  | PermissionError: [Errno 1] Operation not permitted: '/downloads/video/Millomaker/tyzlowaj.tmp'
tubesync  | Rescheduling task Downloading media for "Réparation : Apple VS Samsung" for 0:00:06 later at 2025-01-06 12:44:06.851069+00:00
tubesync  | 2025-01-06 13:44:08,569 [tubesync/WARNING] Download task triggered for media: 6sAv1Dhmt20 (UUID: 75963aba-81cd-4ea7-9aae-1ecacbb6f333) but it has already been marked as downloaded, not downloading again
```

I don't use symlink, but I mount a folder that uses nfsv4_acl (that is also shared via Samba) as the destination video folder, maybe TubeSync cannot understand the rights correctly.
The user running TubeSync do have read/write access rights on that folder, as the video and thumbnail files are downloaded correctly. And it was working without issue with every Youtube video downloaded prior to 29th of December.

As workaround I made a script that goes through all the folders looking for *.tmp files, parse the file to retrieve the thumbnail name, use it as base for the NFO file name, and rename the *.tmp file to that NFO file name. And I run that script before scanning for new files on Plex...

**Comment by meeb** [comment]
@henrikmaurin yes your issue is because `.resolve()` resolves paths to their symlink destinations which in your slightly odd setup resolves your symlinks to your `/Downloaded/...` directory which is outside of the allowed paths.

@tcely I have no objections to using `.absolute()` instead, but thought I'd thread you in given you wrote the change.

**Comment by meeb** [comment]
@ZeblodS your issue is unrelated, you have a `PermissionError` during a `chown` on a file created in `/downloads/...` within your container. Check the permissions of your mapped downloads directory on your host.

**Comment by ZeblodS** [comment]
> @ZeblodS your issue is unrelated, you have a `PermissionError` during a `chown` on a file created in `/downloads/...` within your container. Check the permissions of your mapped downloads directory on your host.

As I said, video file and thumbnail are downloaded in that folder without issue (the tmp file too is downloaded in that folder). The container do see the correct permissions for the PUID/PGID set in the dockerfile.

On the Host
```
root@docker:~# id docker
uid=3002(docker) gid=3002(data) groups=3002(data)
root@docker:~# ls -la /mnt/data-pool/media/Youtube
drwxrwxr-x 42 docker  data   42 Jan  6 15:13  .
drwxrwxr-x 13 zeblods data   16 Jan  2 19:12  ..
[...]
drwxrwxr-x  2 docker  data  170 Jan  6 14:13  Millomaker
[...]
root@server[~]# nfs4xdr_getfacl /mnt/data-pool/media/Youtube
# File: /mnt/data-pool/media/Youtube
# owner: 3002
# group: 3002
# mode: 0o40775
# trivial_acl: false
# ACL flags: none
            owner@:rwxpDdaARWcCos:fd----I:allow
            group@:rwxpDdaARWcCos:fd----I:allow
         everyone@:r-x---a-R-c---:fd----I:allow
```

On the Docker guest
```
root@docker:~# docker exec -it tubesync bash
root@63e2bd45de67:/app# id app
uid=3002(app) gid=3002(app) groups=3002(app)
root@63e2bd45de67:/app# ls -la /downloads/video/
total 10763
drwxrwxr-x 41 app  app    41 Dec 18 15:58  .
drwxr-xr-x  6 root root    6 Jan  6 13:31  ..
[...]
drwxrwxr-x  2 app  app   170 Jan  6 14:13  Millomaker
[...]
```

From the Docker Guest I can create move copy delete files in the /downloads/video/ folder with no error using CLI/bash.
```
root@docker:~# docker exec -u 3002 -it tubesync bash
bash: /root/.bashrc: Permission denied
app@63e2bd45de67:/app$ cd /downloads/video/Millomaker/
app@63e2bd45de67:/downloads/video/Millomaker$ ls -l test
ls: cannot access 'test': No such file or directory
app@63e2bd45de67:/downloads/video/Millomaker$ touch test
app@63e2bd45de67:/downloads/video/Millomaker$ ls -l test
-rwxrwxr-x 1 app app 0 Jan  6 15:33 test
app@63e2bd45de67:/downloads/video/Millomaker$ rm test
app@63e2bd45de67:/downloads/video/Millomaker$ ls -l test
ls: cannot access 'test': No such file or directory
```

Dockerfile
```
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    environment:
      - PUID=3002
      - PGID=3002
      - TZ=Europe/Paris
      - TUBESYNC_RESET_DOWNLOAD_DIR=False
      - DATABASE_CONNECTION=${DATABASE_CONNECTION}
    volumes:
      - /mnt/system-pool/docker/tubesync:/config
      - /mnt/data-pool/media/Youtube:/downloads/video
```

And it was working perfectly fine until the 29th of December. I didn't change any settings, I might just have pulled the latest version of container as I usually do once a week.

**Comment by meeb** [comment]
Can you `chmod a+r somefile` from within the container in your `/downloads/` dir?

**Comment by tcely** [comment]
> I have no objections to using `.absolute()` instead, but thought I'd thread you in given you wrote the change.

https://docs.python.org/3.8/library/pathlib.html?highlight=path#pathlib.Path.resolve

Using `absolute()` is not going to do any actual checking against the filesystem.

I'd consider changing the mount on the host to use the destination of the symbolic link instead.

The mount / symlink situation you are using is unclear. Providing the output from `docker inspect <container>` may help clarify what is happening.

**Comment by ZeblodS** [comment]
> Can you `chmod a+r somefile` from within the container in your `/downloads/` dir?

That's it. Since the Host uses NFSv4_ACL on that folder, you cannot chmod as the rights are forced inherited... Even though "app" has 775 rights in that folder.

```
root@docker:~# docker exec -it tubesync bash
root@63e2bd45de67:/app# cd /downloads/video/Millomaker/
root@63e2bd45de67:/downloads/video/Millomaker# touch test
root@63e2bd45de67:/downloads/video/Millomaker# ls -l test
-rwxrwxr-x 1 root app 0 Jan  6 15:42 test
root@63e2bd45de67:/downloads/video/Millomaker# chmod a+r test
chmod: changing permissions of 'test': Operation not permitted
```

I can't change the usage of NFSv4_ACL on folders shared to Windows as it is defined to work like that in my TrueNAS Scale Host, so I don't know if there's a way to change that behavior without manually comment that "new_filepath.chmod(0o444 | old_mode)" in utils.py.

**Comment by meeb** [comment]
Given forced permissions on remote shares with ACLs is probably quite common, providing the file data is written I can't see an issue with downgrading the `chmod` to emit a warning if it fails rather than hard error.

**Comment by tcely** [comment]
> Given forced permissions on remote shares with ACLs is probably quite common, providing the file data is written I can't see an issue with downgrading the `chmod` to emit a warning if it fails rather than hard error.

I have no issue with changing to a warning when failing to preserve the old permissions.

**Comment by ZeblodS** [comment]
> Given forced permissions on remote shares with ACLs is probably quite common, providing the file data is written I can't see an issue with downgrading the `chmod` to emit a warning if it fails rather than hard error.

That would be great, thanks.

And sorry for having somewhat hijacked that ticket with my issue that wasn't completely related to the original problem.

**Comment by tcely** [comment]
> Relevant parts of my docker compose file
> 
> ```
> volumes:
>       - /Downloaded:/Downloaded
>       - /srv/data/TubeSync:/downloads    
>       - /Downloading/tubesync/cache:/downloads/cache
> ```
> 
> Relevant Symlinks on my server
> ```
> TubeSync -> /Downloaded/Video/Tv
> Downloaded -> /srv/data/Downloaded
> Downloading -> /srv/data/Downloading
> data -> /srv/dev-disk-by-uuid-18c2608f-c77d-4296-bbeb-d354839fac68
> ```

@henrikmaurin
Try changing your volume to: `/srv/data/TubeSync/.:/downloads`

If that resolves the symbolic links on the host side, as it normally would, then you may not need to mount `/Downloaded` in the container anymore.

**Comment by henrikmaurin** [comment]
Ok, I will try that.

**Comment by tcely** [comment]
@henrikmaurin Did you see any results?

**Comment by henrikmaurin** [comment]
Yes! I think the `/.`  did it. Thanks for helping out. 
Initially I had some other problems when trying that... I think I accidentally broke something else in my config by trying to fix this.

**Comment by tcely** [comment]
Great! This issue can be closed then if your symbolic links are now being resolved on the host instead of in the container.

**Comment by henrikmaurin** [comment]
Yes, closing!
I was not aware that of the difference, and up until a few weeks I have not had problems in any of my docker containers using these symlinks
