### ISSUE TITLE
Playlists work but Channels don't

### ISSUE THREAD

**Issue by truckin608** [meeb/tubesync#86]
Been hoping for an app like this so thanks for your hard work much appreciated... 

So I've tried different channels all with the same result. I'm running a docker container on unraid and am using tubesync:v0.9 this is the log error I always get when adding this channel. https://www.youtube.com/channel/UCZDfnUn74N0WeAPvMqTOrtA
any help would be appreciated. 

2021-03-04 17:37:18,418 [tubesync/DEBUG] [youtube:tab] UCZDfnUn74N0WeAPvMqTOrtA: Downloading webpage
2021-03-04 17:37:18,648 [tubesync/DEBUG] [download] Downloading playlist: Spaceinvader One - Videos
2021-03-04 17:37:18,649 [tubesync/DEBUG] [youtube:tab] Downloading page 1
2021-03-04 17:37:18,790 [tubesync/ERROR] ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Rescheduling Index media from source "Spaceinvaderone"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 163, in index_source_task
    raise NoMediaException(f'Source "{source}" (ID: {source_id}) returned no '
common.errors.NoMediaException: Source "Spaceinvaderone" (ID: 2f91ba42-1853-4e48-9a87-f0239c160efc) returned no media to index, is the source key valid? Check the source configuration is correct and that the source is reachable
Rescheduling task Index media from source "Spaceinvaderone" for 0:01:26 later at 2021-03-04 22:38:44.795316+00:00

**Comment by jbat66** [comment]
I to am using docker container on unraid and am using tubesync:v0.9, and I have the same problem. Playlists work but Channels don't

**Comment by Ateroz** [comment]
Click on the videos tab and use that link.
https://www.youtube.com/c/SpaceinvaderOne/videos

**Comment by truckin608** [comment]
same error

2021-03-04 18:48:25,798 [tubesync/DEBUG] [youtube:tab] SpaceinvaderOne: Downloading webpage
2021-03-04 18:48:26,030 [tubesync/DEBUG] [download] Downloading playlist: Spaceinvader One - Videos
2021-03-04 18:48:26,031 [tubesync/DEBUG] [youtube:tab] Downloading page 1
2021-03-04 18:48:26,186 [tubesync/ERROR] ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Rescheduling Index media from source "spaceinvaderone"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 163, in index_source_task
    raise NoMediaException(f'Source "{source}" (ID: {source_id}) returned no '
common.errors.NoMediaException: Source "spaceinvaderone" (ID: e4b80500-3186-41a3-84d1-548e608043b4) returned no media to index, is the source key valid? Check the source configuration is correct and that the source is reachable
Rescheduling task Index media from source "spaceinvaderone" for 0:01:26 later at 2021-03-04 23:49:52.192057+00:00

**Comment by truckin608** [comment]
I redeployed the container pulling the tubesync:latest and all works. found the issue on #84

**Comment by meeb** [comment]
You are correct, this was due to `youtube-dl` requiring an update. This is fixed in `:latest`. Cheers.
